### ISSUE TITLE
Fischer time controls need refactor

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#106]
The way I handle Fischer is by converting it into a fake Canadian byoyomi that I pass on to the engine. I noticed the other day though RoyalZeroSlow was thinking way too long. From the log file it was using all of the time for each move as a maximum, so only the playout limit was stopping it. I thought maybe it was a LZ error, I posted it here https://github.com/leela-zero/leela-zero/issues/2105 but turns out how I'm handling it is wrong and LZ is behaving correctly.

Putting this issue as a reminder to myself, or perhaps someone else will give it a shot on better Fischer support.

**Comment by wonderingabout** [comment]
i feel like with the reject message time converter, and the fischer issue, maybe its time we think how to improve time management by gtp2ogs :+1: 

the "600 seconds" always bugged most users lol

as for game time settings calculation, i use `--noclock` so i dont know if there is even an issue

i hope some people have similar experience and we can start to improve it too :)

**Comment by wonderingabout** [comment]
yes, its what i was talking about, sorry for not being clear :+1:

**Comment by roy7** [comment]
In the other issue, this was my logs from a 30 minute main time + 20 second period in Fischer.

> zeroslowgtp.js:570 [16149 15904111] 11:02:24 >>> kgs-time_settings canadian 1780 20 1
> zeroslowgtp.js:570 [16149 15904111] 11:02:24 >>> time_left black 1917 1
> zeroslowgtp.js:570 [16149 15904111] 11:02:24 >>> time_left white 824 1

It might be easier than I thought. Would we just subtract the period time (20 seconds) from the real time left each move, and report "time_left black <time left less period time> 0"? Ie: Use 0 instead of 1, so it thinks it is in main time all game. So it'll act like "normal" all of the time, and know it has one byoyomi of 20 seconds it can also slide into, which is does since we cut 20 seconds off the time_left command. Then after the move, Fischer adds the 20 seconds back on and we repeat this the next move.

I might test this over the weekend, I think it might really be that simple. I -almost- had this correct... lol. Shame it has been wrong for over a year.

**Comment by roy7** [comment]
This also explains why I used to have timeouts in Fischer and not other loan types. It'd try to use the entire clock to move every move, and if startupbuffer isn't big enough there it goes. Normally during main time it'll try to conserve time based on # of moves left and so on.

**Comment by roy7** [comment]
Fixed in https://github.com/online-go/gtp2ogs/commit/81bcd38acebc2da373c65488ddddc12f3c0b603d.
