### ISSUE TITLE
Startupbuffer better replacement

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#107]
This was bigger than I wanted to try and tackle so I've ignored it, but the --startupbuffer I added as hack to handle the fact the time_left command is sent to the bot while it's starting up on that first move, but the bot won't read the command until the initial startup has completed. This means by the time the bot reads the time_left command, some time has been spent and the info is outdated.

A way around this might be to detect when the prior commands like 'komi' have returned the empty '=' response (so we know bot has initialized and is awake) and then send time_left using actual current time left. In the Chess world the engines seem to have an is_ready command they send and the clock doesn't start until the bot says it is ready.

LZ might eventually create multiple startup threads to process GTP commands even while initializing but a more flexible solution for all bots would be best for gtp2ogs to try and support. Perhaps just sending a mandatory GTP required command (list_commands?) at bot startup and not send the time_left/etc until we have that response is a solution.

Posting this as a reminder one day it maybe needs improved.

**Comment by TokumotoK** [comment]
Thanks for placing this on Issues.
I've been using --startupbuffer and a suspicion is growing in my mind that the seconds specified with this option is deducted not only from the spending time on the first move, but from all the moves.

I actually like this safety margin especially on long games, so please give me an alternative to retain this ability if it is going away while this is being worked on.

Also, list_commands works nicely for solving #68

**Comment by Dorus** [comment]
Yeah i agree here, `--startupbuffer` should probably be renamed to `--startupbuffer` and continue to apply to all moves, but regardless of that, we should detect when a bot is actually ready and only send the correct time then, as roy7 suggested. I think this issue/enhancement is about the latter.

**Comment by roy7** [comment]
@TokumotoK The way it's supposed to work is only apply the startupbuffer on the first move the bot makes, and I believe it is doing so correctly. The toggle is at https://github.com/online-go/gtp2ogs/blob/devel/bot.js#L368 and I do believe looking in my logs I see the change in the time controls after that first move. (Remember it's first move of the bot since starting up, not first move of the game. If you don't use --persist than it would apply every move.)

@Dorus Is correct, basically the long term goal is remove this feature's need completely and do proper detection that the bot is ready to play the first move since startup by using list_commands and getting a response.
