### ISSUE TITLE
Cleanly support a wide range of time settings.

### ISSUE THREAD

**Issue by Dorus** [online-go/gtp2ogs#112]
Admin allows time systems: none, absolute, simple, fisher, canadian and/or byo-yomi.
For none, no future checks are required.
For absoluate, only min and max main time needs to be checked.
For simple, only min and max period time needs to be checked.
For fisher, you need to check initial time against min and max main time. You need to check added time vs min and max period time.
For canadian, you need to min and max main time. You need to check time per x stones against by taking (period time divided by x) and compare against min and max period time. You need to check x stones also against min/max nr of periods.
For byo-yomi you need to check min and max main time, min and max period time, and min and max periods.

So bot admins only need to set allowed `time systems`, `min` and `max main time`, `min` and `max period time`, `min` and `max periods`. A total of 7 settings to support everything.

**Comment by Dorus** [comment]
After some more discussion with @roy7 

There are two roads to take here, and possibly we might want to take both.

One road is to make as few time settings as possible. I'm thinking just a min timer per move and max time per game, and calculate all other limits based on that.

The other option is to allow fine grained control over everything. That means we need a separate period time limit for byo-yomi, canadian and fisher, additional also a max number of stones per period for canadian, while byo-yomi would keep the max periods settings.

Also @wonderingabout pointed out we might want a warning for the bot admin if some time limiting settings are not set. For example an admin might set max period time but not max number of periods, resulting in unintentionally long games if users abuse this limit by picking a ridiculous high number of periods. I'm thinking we should only give that warning if an illogical set of time limiting settings are set.

**Comment by wonderingabout** [comment]
i'll just go ahead and add the warning, its a very rare case and only one text line when gtp2ogs starts, plus very useful to avoid infinite careless games by bot admin

**Comment by Dorus** [comment]
We havn't seen much discussion here, but didn't we introduce separate time settings for every time system a while ago? I think we can close this. Once i introduce the config patch and we get a config file, it wont be much of a hassle anymore to maintain many time settings.

**Comment by wonderingabout** [comment]
up to you @Dorus :+1: 

as for me i still have many things to PR so i'll leave config file to you lol

**Comment by wonderingabout** [comment]
as we started to discuss recently in #287 with @Dorus in:

- https://github.com/online-go/gtp2ogs/pull/287/files?file-filters%5B%5D=.js#r432982164
- https://github.com/online-go/gtp2ogs/pull/287/files?file-filters%5B%5D=.js#r432982239
- https://github.com/online-go/gtp2ogs/pull/287/files?file-filters%5B%5D=.js#r432982794

current gtp2ogs options are not optimal, we'd like to support each time control individually

so instead of checking main time +/- periods +/- periodtime for each timecontrol, we could have a full set of options for each time control, and fall back to maintime/periodtime if not specified by botadmin 

note: (periods exist only for byoyomi (`notification.time_control.time_control.periods`))

for example

````Shell
checkChallengeTimeSettings
    getByoyomiTimeSettingsRejectResult
        check --maintime
        check --periods
        check --periodtime
    getFischerTimeSettingsRejectResult
        check --initialtime (new option, if not used by bot admin fallback to --maintime)
        check --maxtime (new option, if not used by botadmin fallback to --maintime)
        (periods dont exist in fischer, dont check)
        check --incrementtime (new option, if not existing fallback to --periodtime)
    getSimpleTimeSettingsRejectResult
        check --timepermove (new option, if not used by botadmin fallback to --periodtime,
                                            considering there is no maintime, periodtime may be larger so
                                            we dont necessarily want to use periodtime that is based on a large
                                            maintime before starting, therefore it can be short.
                                            similarly, in fischer initial and max time are rechargeable so increment
                                            time is a lot more generous if we just use periodtime)
        
```

etc
