### ISSUE TITLE
Rethinking simple time support

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#116]
So,

While working on the amazing UHMAEAT PR here https://github.com/online-go/gtp2ogs/pull/115, i noticed simple time support is very confusing !!

Because basically : 
- simple time has a main time with `t.main_time`
- but !! simple time also has a period time with `t.per_move` ??

So it has both a maintime and a periodtime, but only one of these ?
how does a botadmin take that into account when using argv ?

also is it safe to use on the GTP side, do bots really understand this time setting well ?

the UHMAEAT can easily re implement simple time if needed, once this issue is cleared

**Comment by Dorus** [comment]
As far as i know, simple time has time per move only.
Absolute time has total time only.

**Comment by wonderingabout** [comment]
@Dorus 

simple time main time : https://github.com/wonderingabout/gtp2ogs/blob/clearer-devel/gtp2ogs.js#L1395

simple time period time : https://github.com/online-go/gtp2ogs/blob/release-5.3/gtp2ogs.js#L1322 and https://github.com/wonderingabout/gtp2ogs/blob/clearer-devel/gtp2ogs.js#L1418

**Comment by roy7** [comment]
From the API docs.

> Simple: Clocks begin with per_move time. After each move the clock is reset to per_move.
> Absolute: The clock is set to total_time and only decreases.

If need be just print out the time control object and see whats in it when you do a simple time game challenge vs an absolute challenge.

**Comment by wonderingabout** [comment]
do i need to use the debugger to do that ? (with `node --inspect` , or maybe just use gtp2ogs `--debug`?)

so simple time really has no main time then, only a period time ?

i'll see next time what i find on this issue

**Comment by Dorus** [comment]
@wonderingabout yeah both methods work. `--debug` on gtp2ogs let you print stack traces togehter with console.log messages, so that's a must have when you are printing debug info.

Printing debug info is very useful when you have trouble reproducing an issue or want to look at a value multiple time during execution.

`node --inspect` however is much more powerful if you want to look at a single situation of the program, or if you want o step trough the code live, as it allows you to see exactly what's going on.

**Comment by roy7** [comment]
Dorus is much more professional than I am. I don't use the debugger/etc. ;) I just add in commands like `this.log("Clock: ", JSON.stringify(clock));` to dump whatever object I need to see into the log.

**Comment by wonderingabout** [comment]
fixed in #124 
@Dorus @roy7
