### ISSUE TITLE
Main things to prioritirize before next master release

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#119]
So :1234: 

history tells us : 
- release 5.1 : march 2017
- release 5.3 : march 2018
- release x.x : xxx xxxx

also a lot of new features, improvements, and fixes, have been released since that time, too much to list them all here

but maybe some have words of important things we may want to look again at before making a new major release 

mostly directed to code contributors so far, but more generally to everyone
@anoek @roy7 @Dorus @windo @lemonsqueeze @tokumotoK

as for me i want to look again at : 

- autohandicap issue in #28 : using `--noautohandicap` removes the issue but doesnt solve it, we want to make automatic handicap dynamically detect min and max handicap, and adjust to rank difference
- simple time support in #116 : does it use main time `t.main_time` or period time `t.per_move`, and how to support it again on gtp2ogs ?
- challenge 404 error #100 and #52 : does not crash the bot so far so been given a low priority, but still occuring every while, sometimes it even loops when gtp2ogs fails to reject a game for some reason, we may want to look again at log behaviour as well as reject behaviour
- remove most warnings and replace them with defaults
- rename `--maxtotalgames` and `--maxactivegames` to the clearer `connected` games
- @roy7 maybe you want to have a look again at the `--persist` behaviour for corr games ? in https://github.com/online-go/gtp2ogs/issues/59
- using a config file instead of argv command line, is easily exportable and much more flexible to add new options, but also easier to read and edit, in #125 

will be updated as we add or point more things

feel free to use this issue as a more general discussion of what we want to do more generally before the release and after

**Comment by TokumotoK** [comment]
#56 --maxpausetime is huge in my mind. 

It appears I have failed to get the point across to roy7 and wonderingabout how important it is to allow (strong) human players to pause a game against bots without forcing a long time setting.  I feel I faced a flat rejection to understand the issue, but am willing to help understanding further. 

Even a simple 24 hour clock for --limitpause without any time setting option is a big improvement, and is a shame not to be included in the next big release.

**Comment by roy7** [comment]
I guess I was thinking if you wanted to let people pause then there was no harm in letting them pause indefinitely? But yeah adding a timeout for max pause length seems like a good option to add.

**Comment by TokumotoK** [comment]
Perhaps viewing GnuGo or Fuego user profile page would convince you how so many (mostly weak) users pause a game and forget.  This makes loading the bot profile page a hassle, and we do depend on the profile page to be viewed by bot users for limitations.

**Comment by wonderingabout** [comment]
@TokumotoK strong or not, i still fail to see why they just cant play a long game like corr or whatever

but if we want to implement that, then we need to also add a --maxpauses (max number of pauses), else the human player can pause the game forever

so : 
--maxpausetime
--maxpauses
- if a game is paused && argv.maxpausetime && !argv.maxpauses) : add ingame chat to notify of pause time allowed and unlimited number of pauses allowed,
- else if a game is paused && argv.maxpausetime && argv.maxpausesadd ingame chat to notify of pause time allowed and max number of pauses allowed,

this may also be an opportunity for us to rethink current pause implementation : 
- add a "pause is not allowed, resuming the game" chat message ingame

**Comment by wonderingabout** [comment]
i tried to look at this : 

i know how to create a time counter, but i dont know how to define current time (i saw .gettime and date in the code, but i dont know how to use them currently), maybe @roy7 can hint me

**Comment by TokumotoK** [comment]
If you are playing a blitzy (shortish) game and if your opponent is a human, pausing the game could be a rude thing to do.  This is not the case if the opponent is a bot that allows you to pause.  A bot could and would wait patiently while you go to bathroom, have dinner, or take a phone call.

Making the time setting long denies your wish to play a blitzy game, so what I'm saying does not apply to corres games.  Hope you are not saying people should not play a short game if there could be 
 unexpected phone calls, or if you have a wife who expects you to come to the dinner table immediately when it is ready.  For a polite player, this is a MAJOR advantage of playing a bot as opposed to playing a human.

**Comment by wonderingabout** [comment]
ok i get what you mean now

another thing i'm getting now is that some bots unlike mine support very fast time setting, so it may make sense to play a fast game against these bots

but still 
so basically it's all about "i want to play my moves very fast but i dont want to use the option of setting long time in case something happens and i want to pause for now. I enjoy more the excitement of a limited time game but i still want to be able to pause it"

To me, both these wishes contradict each other : you either want blitz OR you want to be able to stop

because, in this example, its a blitz game : you are supposed to play all the game in one run, and only if you do that can you get the feel of a fast game
pausing in the middle defeats the purpose of it, 
so if something comes and you want to pause, i think the game looses its feel of a blitz game, so better restart a new one to feel the feel of blitz again, as you said your opponent is a bot so you can start as much times as needed (you can even fork to resume where you left)

but if there is a need for such a feature, we can add it no problem,

but i still think for a player's point of view its a better to stick with what you want : 
- fast game -> all in one run
- not sure -> set long time and play fast or slow
- a problem comes and have to go ? no problem, restart a new one or fork from left position

this makes me realize we should really set --nopauseranked to true by default, or even reverse the argv to --allowpause --allowpauseranked --allowpauseunranked
if a bot admin wants to allow pause he will have the option, but default should be false : pausing games bring much more problems than advantages

**Comment by wonderingabout** [comment]
this makes me realize we should really reverse the argv to --allowpause --allowpauseranked --allowpauseunranked

if a bot admin wants to allow pause he will have the option, but default should be false : pausing games bring much more problems than advantages

looking at gnugo page profile is enough to see most pause games are needlessly paused https://online-go.com/player/58441/GnuGo

human player wants long game ? sure, just set proper corr time and stick with it

**Comment by TokumotoK** [comment]
Why would pause defeats the purpose of ranking?? It sounds like you are still not getting what I'm saying.

Let's assume you take about 5 minutes for bathroom.  Are you saying you should wait 5 minutes for the bot to play each and all the moves for this contingency even if you want a blitz game?  Is it fair for the winner of a major tournament to be decided just because he didn't receive an emergency phone call and the opponent did?

The GnuGo profile page shows so many old games that are paused and left alone, not the current games that are paused for good reasons.  Pausing has been allowed as default for a long time for good reasons.

**Comment by wonderingabout** [comment]
> Let's assume you take about 5 minutes for bathroom. Are you saying you should wait 5 minutes for the bot to play each and all the moves for this contingency even if you want a blitz game?

i dont know not a single bot that takes 5 minutes per move : royalzero is arround 1 sec/move, even royaleela plays in less than 1 min/per move (and plays faster if you reduce time)

also, you can take a shower before or after a blitz game.. (a blitz game lasts 5 minutes at most)

> Is it fair for the winner of a major tournament to be decided just because he didn't receive an emergency phone call and the opponent did?

yes, this is a competition, it's too bad that one person got an emergency, but he will have to withdraw (or if opponent kindly agrees, they can postpone and play another time, but this is only out of kindness)

> Why would pause defeats the purpose of ranking??
ranking aims at estimating people's strengths and weaknesses in limited time for both players, allow players to pause and it becomes freestyle (one person will use bot, one other person will think for hours for every move, etc...)
and i know that if one person wants to cheat he doesnt need that to do it, but its not a reason to give more opportunities

and more importantly, assuming both humans play fair and competitive, a ranked game should never allow pauses, it just loses its competitive point

finally, i forgot to say but on foxwq or tygem do "strong" players pause games ?
i didnt play there for a long time, but i'm sure they dont
so for a ranked game, really allowing pauses dont make any sense (we can leave the option if bot admin truly wants)

i'm sure that if we allow pauses for unranked only, all of a sudden most players wont pause their games anymore, i wonder why..

**Comment by wonderingabout** [comment]
ok this is the first draft i wrote for this : 

didnt test it, but it looks quite good

```
        // this can be viewed as a maxperiods + maxperiodtime problem, where period=pause
        // if maxpausetime and 
        if ((config.maxpausetime || config.maxpauses) && clock.pause.paused && !clock.pause.pause_control["stone-removal"] && !clock.pause.pause_control.system && !clock.pause.pause_control.weekend && !clock.pause.pause_control["vacation-" + clock.black_player_id] && !clock.pause.pause_control["vacation-" + clock.white_player_id]) {

            let pausesNumberConsumed = 0; // max is config.maxpauses
            let remainingPausesNumber = config.maxpauses - pausesNumberConsumed; // when = 0, no more pauses allowed
        
            function pausetimeCountdown() {
                if (remainingPausesNumber = 0) {
                    conn_log(`All ${config.maxpauses} have been consumed, no more pauses allowed, resuming the game`);
                    this.sendchat(`All ${config.maxpauses} pauses allowed have been consumed, no more pauses allowed, resuming the game`);
                } else {
                    let i = Date.now(); // current time, will be refreshed every 1 minutes in the loop
                    let pausetimeInitialTime = Date.now(); // date at which we start pausing the game
                    let pausetimeMaxTime = config.maxpausetime + Date.now(); // after the pause starts, the human player has  config.maxpausetime seconds before the game resumes
                    // we send an ingame sendchat to notify the user of pause settings allowed, in human readable time
                    conn_log(`The game has been paused, pausetime allowed : ${timespanToDisplayString(config.maxpausetime)}, remaining pauses allowed : ${timespanToDisplayString(config.maxpauses)}`);
                    this.sendchat(`The game has been paused, pausetime allowed : ${timespanToDisplayString(config.maxpausetime)}, remaining pauses allowed : ${timespanToDisplayString(config.maxpauses)}`);

                    function pausetimeCheck() {
                        if (i >= pausetimeMaxTime) { // when all allowed pause time is consumed
                            pausesNumberConsumed+=1;
                            remainingPausesNumber = config.maxpauses - pausesNumberConsumed;
                            conn_log(`Just consumed one allowed pause, remaining allowed pauses number is : ${remainingPausesNumber}`);
                            this.sendchat(`Just consumed one allowed pause, remaining allowed pauses number is : ${remainingPausesNumber}`);
                        } else {
                            setTimeout(check, 60000000); //re check every 1 minutes until all pause time is consumed
                        }
                    }
                    pausetimeCheck(); // the code will halt here until one pause period is consumed
                }
            }
        pausetimeCountdown();
      
        }
```

**Comment by wonderingabout** [comment]
submitted an unfinished code attempt here #120

**Comment by Dorus** [comment]
Can we please discuss pausing in a separate topic? It's off topic here.

If ready we should include pausing in the next release, but i do not see a reason why it would be a deal breaker.

**Comment by wonderingabout** [comment]
i was thinking the same, but i dont have write rights to hide messages

anyways, let's continue the discussion here for interested people #56

**Comment by wonderingabout** [comment]
so i'll focus on #28, then for #116 i need to have everyone's feedback on what should be done, and finally i'll try to implement autosend games feature if possible (if not, i'll PR it in next devel, likely to take some time)

**Comment by wonderingabout** [comment]
so first thing, autohandicap issue is addressed in #121 , looking forward to being able to detect and add bot rnak into that, will fix the issue

**Comment by wonderingabout** [comment]
moving on to these now : 

- remove most warnings and replace them with defaults
- rename `--maxtotalgames` and `--maxactivegames` to the clearer `connected` games
- @roy7 maybe you want to have a look again at the `--persist` behaviour for corr games ? in https://github.com/online-go/gtp2ogs/issues/59

**Comment by windo** [comment]
With the amount of configuration options we're discussing, it sounds like we should switch from command line arguments to config files.

**Comment by wonderingabout** [comment]
oh, thats definitely a nice idea i think

phoenixgo is doing the same for example, and the ability to export my config files and switch them instantly is very nice, see : 

https://github.com/wonderingabout/PhoenixGo/tree/faqv2-bazel-master

and : 

https://github.com/wonderingabout/PhoenixGo/blob/faqv2-bazel-master/etc/mcts_1gpu.conf

@windo @roy7 @Dorus 

i love this idea really

**Comment by wonderingabout** [comment]
these 2 are now done !, with a few extra things added too !!

moving on to simple time issue in #116 now !

**Comment by wonderingabout** [comment]
fixed simple time control re added in #124

**Comment by wonderingabout** [comment]
i'm also definitely looking at this if possible : 

https://github.com/online-go/gtp2ogs/issues/125

would be a major improvement

**Comment by wonderingabout** [comment]
this issue is getting too aspecific so i'm closing it for now
