### ISSUE TITLE
Polling for and logging in-game chat messages

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#126]
My bots sometimes do silly thinks in-game (resign at the wrong time, not resign when they've clearly lost, they could get stuck and not play) and I encourage users to let me know when that happens. The most convenient place to do that would be directly in the game discussion.

Now, I could write a separate API client to trawl through the recent games and pull up any games with comments in the game chat. But since it sounds like it might be useful to other bot admins as well, I'm also considering if maybe this should be a feature of `gtp2ogs`, kind of like the friend request auto-accept.

If this sounds good to you, then I'd like to trigger a callback to run a small number of minutes after a game has ended and pull the game discusssion. At that point I think `gtp2ogs` could either log the full text of the discussion or just log the game ID and a note that there are chat messages.

Does that sound feasible and potentially useful? Or should I look into doing it outside `gtp2ogs`?

**Comment by wonderingabout** [comment]
i dont understand all the details, but from what i understand you want to be more interactive with the users right ?

i also think if we could be more talkative it would make user experience better, and i did it at a much smaller scale in #118 

maybe you want to start with enhancing the greeting and farewell messages @windo 

i dont understand all the details of your idea so sorry i cant be of much help !! :laughing:

**Comment by wonderingabout** [comment]
btw maybe you want to have more interactive and quick chat on discord with other bot admins https://discord.gg/HZ23Cp9

this does not replace the github for long comments and discussion

but more like quick talk and fast replies :+1:

**Comment by roy7** [comment]
Isn't there an even that fires out to a client via the API whenever a chat message happens? Maybe gtp2ogs doesn't even have a placeholder for it since it's never been used, but we could add that. Then you can add an option to log chat messages, either to a single file or the debug log or per-game or whatever?

Yes look at https://ogs.readme.io/docs/real-time-api#gameidchat.

**Comment by windo** [comment]
Hmm. It does not seem the events are delivered as-is. I tried to vaguely follow some things I saw happening in the `online-go` repository (like getting the chat_auth from "ui/config" and sending it in `authenticate` message and also a `chat/connect` message) but I guess I'm not understanding how that's supposed to work :(

**Comment by roy7** [comment]
I think that stuff is for sending messages (we are already authenticated enough to use the sendChat() command). Perhaps extra steps needed to send private messages.

But simply reading chat messages from a game should be doable. Although after we disconnect from the game after it is over we wouldn't get the chat message events any more.

My thought was you'd add an event handler like

`this.socket.on('game/' + game_id + '/chat', (chat) => {`

And check if chat.message.body was a string and if so, log it?

**Comment by windo** [comment]
I tried doing that but wasn't getting any messages:

https://github.com/windo/gtp2ogs/tree/chat

I hope I'm just missing something tiny, but I wasn't able to get any chat messsages to appear.

BTW, I discovered I can do:

```
export DEBUG='socket.io*'
```

To get the websocket client log all sent/received messages. But no luck seeing neither PMs or game chats anywhere :(

**Comment by roy7** [comment]
@anoek Can you drop a hint about getting game chat messages? (When people speak in game chat room.)

**Comment by windo** [comment]
I tried tracing online-go.com in javascript debugger, but still doesn't seem to get any chat messages:

https://github.com/windo/gtp2ogs/tree/chat

I think I do need chat_auth (at least OGS javascript provides it). And the one I was providing was not correct because the call to `/api/v1/ui/config` is not authenticated to the bot so returns the auth tokens for a guest account. And I don't know how to use the `apikey` or `jwt` to authenticate the GET request to `/ui/config`. I tried passing them in as Bearer tokens but that did not seem to work.

Honestly, I don't understand how authentication works. We pass the apikey to realtime API and get back the jwt and then pass in the JWT as a query parameter to the non-realtime API too - so jwt is the authentication mechanism? But it does not seem to work for `/ui/config` unless I was messing something up.

**Comment by windo** [comment]
I got some chatting (both PMs and game chats) to come through by manually looking up the `chat_auth` key from `/api/v1/ui/config` for the bot and making sure it was in the `authenticate` ws event sent to server (and requesting chats in the `game/connect` too).

But I don't know how to get the `ui/config`. When I just try to `get()` it with the normal `auth()` call as parameters, I get a `ui/config` for a guest user (ex `guest00152`), as if I wasn't authenticated. Trying it with post throws this exception:

```
Feb 26 08:14:46 !!!!! connection.js:914              #  401 - {"detail":"Authentication credentials were not provided."}
Feb 26 08:14:46 !!!!! connection.js:915              Error
    at conn_log (/home/siim/projects/gtp2ogs/connection.js:915:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This is how I'm doing it:

```
post(api1("ui/config"), this.auth({})).then((ui_config) => {
    conn_log(ui_config);
}).catch(conn_log);
```

So yep, I think I need guidance from @anoek as to how to get connected to game chats using the bot authentication.
