### ISSUE TITLE
Bug Twice on a row the same day : "killing bot because of gamedata packet after bot was started"

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#128]
@roy7 @Dorus @windo 

starting a forked game against royallz-elf

game connects, then gtp2ogs stops the bot before we submit a move

![weirdbug](https://user-images.githubusercontent.com/38690718/52664604-b5092f80-2f09-11e9-8039-6c64db42fba0.png)

fixed after ctrl+c (stop gtp2ogs) then restart with the exact same command

for reference game is here : https://online-go.com/game/16548505

**Comment by roy7** [comment]
What should happen is the bot is restarted fresh after the state is reloaded. Is that happening? Now and then server will send an 'extra' gamedata packet and restarting the bot is how I deal with it.

**Comment by wonderingabout** [comment]
it didnt happen

after that the bot stayed dead

i noticed that when i came back 30 minutes later, was expecting the game to be in midgame already

i'll copy paste the log here

fixed after manual restart of gtp2ogs @roy7

**Comment by wonderingabout** [comment]
oh nvm i cant,

terminal deleted it, log too big

**Comment by roy7** [comment]
I hope a recent change hasn't broken this. I've had gamedata restarts on my bots work correctly ever since I put it into place. :(

**Comment by wonderingabout** [comment]
this is the first time it happens to me too

but, its not a bad thing if that were the case
will be an opportunity to improve things again

**Comment by wonderingabout** [comment]
@roy7 @anoek theres definitely a bug now, happened again just now

the position is d4 black + k10 white, starting a forked game, my bot is black, bot crashes : 

log dump 
```
Feb 12 22:01:34   [Game 16549554]  Move 103  Resigning
Feb 12 22:01:35   [Game 16549554]  Move 103  gamedata     W   RoyalLZ-ELF  [19x19]    
Feb 12 22:01:35   [Game 16549554]  Move 103  Game over.   Result: B+R         L
Feb 12 22:01:35   [27257] Stopping bot 
Feb 12 22:01:36   [Game 16549554]  Move 103  Disconnecting from game.
Feb 12 22:13:36   [Game 16549999]            Connecting to game.
Feb 12 22:13:36   [Game 16549999]            gamedata       B RoyalLZ-ELF  [19x19]    
Feb 12 22:13:36   [Game 16549999]            Starting new bot process [31371]
Feb 12 22:13:36   [Game 16549999]            State loading for new bot
Feb 12 22:13:36   [Game 16549999]            genmove black
Feb 12 22:13:36 !!!!! [31371] stderr: I0212 22:13:36.423923 31371 mcts_main.cc:75] load config succ:
Feb 12 22:13:36 !!!!! [31371] stderr: num_eval_threads: 1
Feb 12 22:13:36 !!!!! [31371] stderr: num_search_threads: 8
Feb 12 22:13:36 !!!!! [31371] stderr: max_search_tree_size: 400000000
Feb 12 22:13:36 !!!!! [31371] stderr: max_children_per_node: 64
Feb 12 22:13:36 !!!!! [31371] stderr: max_simulations_per_step: 3200
Feb 12 22:13:36 !!!!! [31371] stderr: eval_batch_size: 4
Feb 12 22:13:36 !!!!! [31371] stderr: eval_wait_batch_timeout_us: 100
Feb 12 22:13:36 !!!!! [31371] stderr: model_config {
Feb 12 22:13:36 !!!!! [31371] stderr: train_dir: "/home/amd2018/PhoenixGo/ckpt/"
Feb 12 22:13:36 !!!!! [31371] stderr: enable_tensorrt: true
Feb 12 22:13:36 !!!!! [31371] stderr: tensorrt_model_path: "/home/amd2018/PhoenixGo/ckpt/zero.ckpt-20b-v1.FP32.PLAN"
Feb 12 22:13:36 !!!!! [31371] stderr: }
Feb 12 22:13:36 !!!!! [31371] stderr: gpu_list: "0"
Feb 12 22:13:36 !!!!! [31371] stderr: c_puct: 2.5
Feb 12 22:13:36 !!!!! [31371] stderr: virtual_loss: 1
Feb 12 22:13:36 !!!!! [31371] stderr: enable_resign: true
Feb 12 22:13:36 !!!!! [31371] stderr: v_resign: -0.7
Feb 12 22:13:36 !!!!! [31371] stderr: dirichlet_noise_alpha: 0.03
Feb 12 22:13:36 !!!!! [31371] stderr: dirichlet_noise_ratio: 0.25
Feb 12 22:13:36 !!!!! [31371] stderr: policy_temperature: 0.67
Feb 12 22:13:36 !!!!! [31371] stderr: inherit_default_act: true
Feb 12 22:13:36 !!!!! [31371] stderr: early_stop {
Feb 12 22:13:36 !!!!! [31371] stderr: check_every_ms: 100
Feb 12 22:13:36 !!!!! [31371] stderr: sims_factor: 1
Feb 12 22:13:36 !!!!! [31371] stderr: sims_threshold: 2000
Feb 12 22:13:36 !!!!! [31371] stderr: }
Feb 12 22:13:36 !!!!! [31371] stderr: unstable_overtime {
Feb 12 22:13:36 !!!!! [31371] stderr: time_factor: 0.3
Feb 12 22:13:36 !!!!! [31371] stderr: }
Feb 12 22:13:36 !!!!! [31371] stderr: behind_overtime {
Feb 12 22:13:36 !!!!! [31371] stderr: time_factor: 0.3
Feb 12 22:13:36 !!!!! [31371] stderr: }
Feb 12 22:13:36 !!!!! [31371] stderr: time_control {
Feb 12 22:13:36 !!!!! [31371] stderr: c_denom: 20
Feb 12 22:13:36 !!!!! [31371] stderr: c_maxply: 40
Feb 12 22:13:36 !!!!! [31371] stderr: reserved_time: 1
Feb 12 22:13:36 !!!!! [31371] stderr: }
Feb 12 22:13:36 !!!!! [31371] stderr: I0212 22:13:36.424535 31371 mcts_engine.cc:85] MCTSEngine: waiting all eval threads init
Feb 12 22:13:36 !!!!! [31371] stderr: I0212 22:13:36.584336 31372 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:36 !!!!! [31371] stderr: I0212 22:13:36.584362 31372 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:36 !!!!! [31371] stderr: I0212 22:13:36.584365 31372 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:36 !!!!! [31371] stderr: I0212 22:13:36.584368 31372 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:37   [Game 16549999]            gamedata       B RoyalLZ-ELF  [19x19]    
Feb 12 22:13:37   [Game 16549999]            Killing bot because of gamedata packet after bot was started
Feb 12 22:13:37   [31371] Stopping bot 
Feb 12 22:13:37   [Game 16549999]            Starting new bot process [31390]
Feb 12 22:13:37   [Game 16549999]            State loading for new bot
Feb 12 22:13:37   [Game 16549999]            genmove black
Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.228462 31390 mcts_main.cc:75] load config succ:
Feb 12 22:13:37 !!!!! [31390] stderr: num_eval_threads: 1
Feb 12 22:13:37 !!!!! [31390] stderr: num_search_threads: 8
Feb 12 22:13:37 !!!!! [31390] stderr: max_search_tree_size: 400000000
Feb 12 22:13:37 !!!!! [31390] stderr: max_children_per_node: 64
Feb 12 22:13:37 !!!!! [31390] stderr: max_simulations_per_step: 3200
Feb 12 22:13:37 !!!!! [31390] stderr: eval_batch_size: 4
Feb 12 22:13:37 !!!!! [31390] stderr: eval_wait_batch_timeout_us: 100
Feb 12 22:13:37 !!!!! [31390] stderr: model_config {
Feb 12 22:13:37 !!!!! [31390] stderr: train_dir: "/home/amd2018/PhoenixGo/ckpt/"
Feb 12 22:13:37 !!!!! [31390] stderr: enable_tensorrt: true
Feb 12 22:13:37 !!!!! [31390] stderr: tensorrt_model_path: "/home/amd2018/PhoenixGo/ckpt/zero.ckpt-20b-v1.FP32.PLAN"
Feb 12 22:13:37 !!!!! [31390] stderr: }
Feb 12 22:13:37 !!!!! [31390] stderr: gpu_list: "0"
Feb 12 22:13:37 !!!!! [31390] stderr: c_puct: 2.5
Feb 12 22:13:37 !!!!! [31390] stderr: virtual_loss: 1
Feb 12 22:13:37 !!!!! [31390] stderr: enable_resign: true
Feb 12 22:13:37 !!!!! [31390] stderr: v_resign: -0.7
Feb 12 22:13:37 !!!!! [31390] stderr: dirichlet_noise_alpha: 0.03
Feb 12 22:13:37 !!!!! [31390] stderr: dirichlet_noise_ratio: 0.25
Feb 12 22:13:37 !!!!! [31390] stderr: policy_temperature: 0.67
Feb 12 22:13:37 !!!!! [31390] stderr: inherit_default_act: true
Feb 12 22:13:37 !!!!! [31390] stderr: early_stop {
Feb 12 22:13:37 !!!!! [31390] stderr: check_every_ms: 100
Feb 12 22:13:37 !!!!! [31390] stderr: sims_factor: 1
Feb 12 22:13:37 !!!!! [31390] stderr: sims_threshold: 2000
Feb 12 22:13:37 !!!!! [31390] stderr: }
Feb 12 22:13:37 !!!!! [31390] stderr: unstable_overtime {
Feb 12 22:13:37 !!!!! [31390] stderr: time_factor: 0.3
Feb 12 22:13:37 !!!!! [31390] stderr: }
Feb 12 22:13:37 !!!!! [31390] stderr: behind_overtime {
Feb 12 22:13:37 !!!!! [31390] stderr: time_factor: 0.3
Feb 12 22:13:37 !!!!! [31390] stderr: }
Feb 12 22:13:37 !!!!! [31390] stderr: time_control {
Feb 12 22:13:37 !!!!! [31390] stderr: c_denom: 20
Feb 12 22:13:37 !!!!! [31390] stderr: c_maxply: 40
Feb 12 22:13:37 !!!!! [31390] stderr: reserved_time: 1
Feb 12 22:13:37 !!!!! [31390] stderr: }
Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.229117 31390 mcts_engine.cc:85] MCTSEngine: waiting all eval threads init
Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383904 31391 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383939 31391 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383944 31391 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383949 31391 trt_zero_model.cc:41] Added linear block of size 1478656
Feb 12 22:13:37 !!!!! [31390] stderr: E0212 22:13:37.497542 31391 trt_zero_model.cc:39] cudnnEngine.cpp (56) - Cuda Error in initializeCommonContext: 4
Feb 12 22:13:37 !!!!! [31390] stderr: terminate called after throwing an instance of 'nvinfer1::CudaError'
Feb 12 22:13:37 !!!!! [31390] stderr: what():  std::exception
Feb 12 22:13:37 !!!!! [31390] stderr: *** Aborted at 1550006017 (unix time) try "date -d @1550006017" if you are using GNU date ***
Feb 12 22:13:37 !!!!! [31390] stderr: PC: @                0x0 (unknown)

```

**Comment by wonderingabout** [comment]
![bug1](https://user-images.githubusercontent.com/38690718/52669830-70849080-2f17-11e9-9f1c-97593df4d336.png)
![bug2](https://user-images.githubusercontent.com/38690718/52669829-6febfa00-2f17-11e9-96d2-f00fa11bb7a2.png)
![bug3](https://user-images.githubusercontent.com/38690718/52669828-6febfa00-2f17-11e9-9a76-2528f624704f.png)

**Comment by wonderingabout** [comment]
i'm glad we noticed this before the major release

no idea how old this bug is

restarting fixes it, bot plays normally, see : 
https://online-go.com/game/16549999

**Comment by wonderingabout** [comment]
settings used for the games : 

![samesettings](https://user-images.githubusercontent.com/38690718/52670675-711e2680-2f19-11e9-9ee6-80f690de5959.png)

**Comment by wonderingabout** [comment]
when my bot is white no issue

when my bot is black 2 games 2 bugs

**Comment by wonderingabout** [comment]
will try a crash test of 10 games next time

**Comment by roy7** [comment]
From the error, the bot is crashing. It isn't in gtp2ogs. Maybe the startup buffer is causing the amount of time it has left to be too low and Phoenix go can't handle that? I'm not exactly sure, but you can see that Cuda error and that's totally an internal problem with the bot.

**Comment by wonderingabout** [comment]
i'm using `--noclock` though

**Comment by wonderingabout** [comment]
does startup error still apply if `--noclock` (never used before, dont know)

**Comment by wonderingabout** [comment]
will look into this again next time, sleep time :+1:

**Comment by roy7** [comment]
I was just trying to make a wild guess. But the Cuda infer error is internal to the bot. It isn't gtp2ogs crashing. You might post an issue at Phoenix go.

**Comment by wonderingabout** [comment]
hmm, if thats the case i have an easy way to debug this

in phoenixgo you can add `--init_moves`

i'll try that in GTP mode next time and see if this position really crashes the bot, which i honestly doubt

will come here again with the results,

similar as https://github.com/Tencent/PhoenixGo/issues/83

**Comment by roy7** [comment]
> Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.229117 31390 mcts_engine.cc:85] MCTSEngine: waiting all eval threads init
> Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383904 31391 trt_zero_model.cc:41] Added linear block of size 1478656
> Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383939 31391 trt_zero_model.cc:41] Added linear block of size 1478656
> Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383944 31391 trt_zero_model.cc:41] Added linear block of size 1478656
> Feb 12 22:13:37 !!!!! [31390] stderr: I0212 22:13:37.383949 31391 trt_zero_model.cc:41] Added linear block of size 1478656
> Feb 12 22:13:37 !!!!! [31390] stderr: E0212 22:13:37.497542 31391 **trt_zero_model.cc:39] cudnnEngine.cpp (56) - Cuda Error in initializeCommonContext: 4**
> Feb 12 22:13:37 !!!!! [31390] stderr: **terminate called after throwing an instance of 'nvinfer1::CudaError'**
> Feb 12 22:13:37 !!!!! [31390] stderr: what():  std::exception
> Feb 12 22:13:37 !!!!! [31390] stderr: *** Aborted at 1550006017 (unix time) try "date -d @1550006017" if you are using GNU date ***
> 

You may want to post an issue on Phoenix Go Github and see what they tell you. These are errors internal to Phoenix Go itself. :(

**Comment by windo** [comment]
Though I think it would be nice if `gtp2ogs` handled bot crashes better. I think currently it just gets stuck. I have a commit with some work towards this but nearly enough.

What should be the correct behavior when the bot crashes? Should `gtp2ogs` wait a little bit of time and then try to start the bot back up again? What if it keeps crashing, resign? Or would it be good enough to just keep retrying every some number of seconds and have the administrator interfere (and let the games time out)?

**Comment by Dorus** [comment]
Resign makes zero sense. Can it detect crashes? If so it should just restart the bot, possibly with incremental relaxed timing. The game itself might or might not time out before the bot successfully restart or admin interferes.

Imagine throwing away two dozen correspondence games because your gpu overheated.

**Comment by wonderingabout** [comment]
@windo 

after a crash, the natural behaviour for us bot admins is to restart the bot and try again

so i would like if after a crash, gtp2ogs sends a sendchat ingame "sorry, the bot just crashed, trying to restart 1/5 try"

if crash again, trying again 3 or 5 times

after 5th try : 

"so i would like if after a crash, gtp2ogs sends a sendchat ingame "sorry, the bot just crashed, failed to  restart after 5 tries, sorry"

**Comment by wonderingabout** [comment]
ideally, in a dream world, after that the bot would sendchat : 

"you can leave the game safely, the bot admin has been notified of this issue"

**Comment by wonderingabout** [comment]
as for me i'll try the position that made phoenixgo crash

**Comment by wonderingabout** [comment]
as i lost interest in this issue, and bot are killed in case of crash, closing this for now :+1:
