### ISSUE TITLE
server disconnects can cause games to get stuck

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#139]
It looks like if a bot is in the middle of the move and the OGS server is restarted, the bot will get stuck and never move. The gtp2ogs logs in this case look like:

```
Feb 21 10:06:56   game.js:474                    [Game 16674926]  Move 23   genmove white
Feb 21 10:06:56   bot.js:130                     [26894] Generating move for game 16674926
Feb 21 10:06:56   bot.js:130                     [26894] >>> genmove white
Feb 21 10:06:56   bot.js:130                     [26894] <<< =
Feb 21 10:06:56   connection.js:1659             #  Disconnected from server
Feb 21 10:06:56   connection.js:1659             #  disconnectFromGame 16674226
Feb 21 10:06:56   bot.js:130                     [24595] Stopping bot
Feb 21 10:06:56   bot.js:130                     [24595] Attempting to send to dead bot: quit
Feb 21 10:06:56   game.js:474                    [Game 16674226]  Move 151  Disconnecting from game.
Feb 21 10:06:56   connection.js:1659             #  disconnectFromGame 16674875
Feb 21 10:06:56   bot.js:130                     [24246] Stopping bot
Feb 21 10:06:56   bot.js:130                     [24246] Attempting to send to dead bot: quit
Feb 21 10:06:56   game.js:474                    [Game 16674875]  Move 134  Disconnecting from game.
Feb 21 10:06:56   connection.js:1659             #  disconnectFromGame 16674899
Feb 21 10:06:56   bot.js:130                     [26314] Stopping bot
Feb 21 10:06:56   bot.js:130                     [26314] Attempting to send to dead bot: quit
Feb 21 10:06:56   game.js:474                    [Game 16674899]  Move 71   Disconnecting from game.
Feb 21 10:06:56   connection.js:1659             #  disconnectFromGame 16674926
Feb 21 10:06:56   bot.js:130                     [26894] Stopping bot
Feb 21 10:06:56   bot.js:130                     [26894] Attempting to send to dead bot: quit
Feb 21 10:06:56   game.js:474                    [Game 16674926]  Move 23   Disconnecting from game.
Feb 21 10:06:56   bot.js:130                     [24246] Bot exited
Feb 21 10:06:56   bot.js:130                     [24595] Bot exited
Feb 21 10:06:56   bot.js:130                     [26314] Bot exited
Feb 21 10:06:56   bot.js:130                     [26894] Bot exited
Feb 21 10:06:56   game.js:474                    [Game 16674926]  Move 23   We may need to move but were not able to. Re-connect to trigger action based on game state.
Feb 21 10:06:56   connection.js:1659             #  Connected
Feb 21 10:06:57   connection.js:1659             #  Bot is username: amybot-beginner
Feb 21 10:06:57   connection.js:1659             #  Bot is user id: 605979
```

And later, it is just:

```
Feb 21 10:06:57   connection.js:1659             #  active_game: {"id":16674926,"phase":"play","name":"Friendly Match","player_to_move":605979,"width":13,"height":13,"move_number":23,"paused":0,"private":false,"black":{"username":"buptmsg","id":617390,"rank":10,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":170.17412470441053,"rating":1260.3555783124457,"volatility":0.05999420067734499,"games_played":6}}},"white":{"username":"amybot-beginner","id":605979,"rank":10,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":74.35406198288477,"rating":1181.6377595039387,"volatility":0.06519921960671782,"games_played":18146}}},"time_per_move":89280}
Feb 21 10:06:57   game.js:474                    [Game 16674926]            Connecting to game.
...
Feb 21 10:07:35   game.js:474                    [Game 16674926]  Move 23   Undo requested 23
Feb 21 10:07:35   game.js:474                    [Game 16674926]            Undo requested 23
```

So clearly the bot is the next to move, but does not even start the bot process. Predictably, the player is confused and tries to request an undo because it is the only button they have in the UI.

I've seen 3 of these in the past few days. I do run with my [bot-crash](https://github.com/windo/gtp2ogs/tree/bot-crash) branch so it's possible it is just that some change in there. But at the very least, I think I'll add a test case for server restarts even if this is just because of bug in my branch.

**Comment by wonderingabout** [comment]
the tests have already been helpful to warn notice of several last minute typos in code, looking forward to more tests improvement, nice :+1:

**Comment by roy7** [comment]
I'll try to look at it this evening, an initial thought is I wonder if we need to go back to just killing the bot process directly instead of trying to exit cleanly with the quit command.

The other bots who were not in the middle of a move exited and restarted properly right?

**Comment by windo** [comment]
Yes. In the bot-crash branch (where I observe this) I already do both `quit` and a `kill()`. I'll take a stab at figuring this out too - might be something in my branch.

**Comment by windo** [comment]
I tried injecting spurious restarts and playing a game, in connection.js:

```
setInterval(()=>{
    socket.close();
    socket.open();
}, 10000);
```

But that game played just fine.

I also tried constructing a test case where a connection has a `disconnect` event in the middle of the `genmove` and reconnected immediately after - also worked just fine (though I probably did not simulate the server behavior entirely correctly so that's less surprising).

So I'm unable to reproduce this outside of actual real server restarts. I wonder if an actual server restarts could be introducing a difference in server behavior somehow.

Based on the logs, it seems the server is sending an `active_game` event but either the `game/.../gamedata` event is not sent, the `Game` is not properly subscribed for them when it is sent or the Game considers itself `connected = false` (only set in `disconnect()`) when the gamedata arrives.

I've added some extra logging locally to maybe tease out which one of those is happening.

**Comment by roy7** [comment]
Thanks for the hard work @windo. If you're able to track to isolate it maybe we can find a way to improve things on the server side if a server restart can leave us in an uncertain state on the bot side.

**Comment by windo** [comment]
I had one of these with extra logging. After the reconnect, there are a bunch of active_game messages for all the games:

```
Feb 24 04:54:28   connection.js:1694             #  Connected
Feb 24 04:54:29   connection.js:1694             #  Bot is username: amybot-ddk
Feb 24 04:54:29   connection.js:1694             #  Bot is user id: 608184
Feb 24 04:54:29   connection.js:1694             #  active_game: {"id":16718316,"phase":"play","name":"친선 대국","player_to_move":608184,"width":19,"ht":19,"move_number":0,"paused":0,"private":false,"black":{"username":"amybot-ddk","id":608184,"rank":14,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":76.36645275363188,"rating":1635.6164732626428,"volatility":0.052230588415396004,"games_played":4780}}},"white":{"username":"simple.korea000","id":452282,"rank":7,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":177.15642534593684,"rating":1545.0488133834665,"volatility":0.059986042955953216,"games_played":4}}},"time_per_move":37}
Feb 24 04:54:29   game.js:474                    [Game 16718316]            Connecting to game.
Feb 24 04:54:29   game.js:474                    [Game 16718316]            Connecting to game 16718316
Feb 24 04:54:29   connection.js:1694             #  active_game: {"id":16718194,"phase":"play","name":"Friendly Match","player_to_move":608184,"width":9,"height":9,"move_number":10,"paused":0,"private":true,"black":{"username":"amybot-ddk","id":608184,"rank":13,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":75.16903964229677,"rating":1646.2928557631021,"volatility":0.052209351259886884,"games_played":4781}}},"white":{"username":"Kazen","id":609839,"rank":9,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":132.95363255949457,"rating":1284.2544958992428,"volatility":0.06003241540079977,"games_played":8}}},"time_per_move":89280}
Feb 24 04:54:29   game.js:474                    [Game 16718194]            Connecting to game.
Feb 24 04:54:29   game.js:474                    [Game 16718194]            Connecting to game 16718194
Feb 24 04:54:29   connection.js:1694             #  active_game: {"id":16718157,"phase":"play","name":"친선 대국","player_to_move":608184,"width":19,"ht":19,"move_number":140,"paused":1550983948266,"private":false,"black":{"username":"amybot-ddk","id":608184,"rank":14,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":75.16903964229677,"rating":1646.2928557631021,"volatility":0.052209351259886884,"games_played":4781}}},"white":{"username":"kch6114","id":616645,"rank":11,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":99.2678955908981,"rating":1548.6344760873355,"volatility":0.06007693031413064,"games_played":19}}},"time_per_move":50}
Feb 24 04:54:29   game.js:474                    [Game 16718157]            Connecting to game.
Feb 24 04:54:29   game.js:474                    [Game 16718157]            Connecting to game 16718157
...
```

And then gamedata events start coming in, but never for the stuck game, in this case `16718194`. In fact, all the other `active_game` events end up getting a matching `gamedata`, except for this one game in this case.

Later on, my little game state dumper just keeps on logging:

```
Feb 24 05:02:41   connection.js:1694             #  Connected to game ID: 16718194
Feb 24 05:02:41   connection.js:1694             #  No game state
```

And the game never gets out of this state.

Sooo, as a quick fix, I'd just be inclined to periodically look for supposedly "connected" games with missing state and disconnect-reconnect them to hopefully get the server to send the gamedata.

**Comment by wonderingabout** [comment]
this is way too technical for me, but more fixes can only be good and very appreciated :+1: 

big thanks as always @windo :100:

**Comment by roy7** [comment]
@windo Is it the case though that only a bot currently thinking about its move is one that gets stuck? ie: We get a gamedata packet if it wasn't our turn at server restart, but we don't get a gamedata packet if it was out turn?

**Comment by roy7** [comment]
@anoek Could you review the log above and see if you have any thoughts on what might cause some games to not get a gamedata packet after a server restart? It might be limited to games that are our turn vs opponent's turn.

**Comment by windo** [comment]
In this one server restart I looked into , it only happened that tis one game did not get a gamedata and it was the bot's' turn. I think there was another game where it was the bot's turn where we got the gamedata for the game.

I think with the logging in this PR, we should be able to make more definitive statements about which games might not get the gamedata packet and how frequently.

**Comment by windo** [comment]
I'm not sure the problem is with the server restarting, it could just be that the `gtp2ogs` connection drops. From logs I can see that the disconnects do not always happen at the same time for both of my bots.
