### ISSUE TITLE
Warning: /--komi auto/ has been renamed to /--komi automatic/

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#149]
This warning happens even when no --komi argument is provided.

**Comment by wonderingabout** [comment]
yes, i'll fix it myself @roy7 :+1: 

i know how to actually write and use arrays now (a little) :+1:

**Comment by wonderingabout** [comment]
fixed in #150

**Comment by wonderingabout** [comment]
@roy7 can you close :running_man:
