### ISSUE TITLE
Use two different commands in one game

### ISSUE THREAD

**Issue by jillybob** [online-go/gtp2ogs#154]
Different AI have different strengths. For example, ELF and Minigo are strong in opening, and PhoenixGo is strong in mid-game, while Pangafu's GX nets avoid playing slack moves in end-game Therefore, it's ideal to be able to use more than 1 AI in a single game. 

Following a chat with @wonderingabout  on Discord, a way to code this is by

```
Let AI 1 play the first 50 moves

Then

Let AI 2 play moves from 51-999 
```

Other advantages are that a bot that plays quickly can be used first (Eg. an AI that uses an opening-book) followed by a stronger, slower AI later.

**Comment by wonderingabout** [comment]
i think its a great idea @jillybob 

more than diversity advantage, my bot is very slow, so sometimes i may want to let another AI play the first moves, for example lz-minigo is stronger in the opening than native phoenixgo, and its play speed is much much much faster 

i think it should not be too code right @roy7 @Dorus @windo 

something like

// check every move the move number
if (game move number <50) -> bot = bot commands 1
else if (game move number >=50) -> kill bot 1, start bot 2 = bot commands 2

the general idea
maybe it will be easier with the latest kill bot code @windo provided last time :+1: 

i totally like and am interested about this idea

**Comment by wonderingabout** [comment]
actually this may be easier when we implement config files like @Dorus showed

**Comment by anoek** [comment]
I would think this would be better implemented by the executable / script being called. If I were to do this, I would whip together a quick python script (or whatever your favorite language is for doing these things), in there I would relay the input from gtp2ogs to AI 1 / AI 2 appropriately based on whatever logic I wanted.

**Comment by wonderingabout** [comment]
i am not very knowledgeable, but to mention in this talk, @Dorus  started a configfile node implementation here 

https://github.com/Dorus/gtp2ogs/tree/configFile

would we still want a separate script if we load every config setting in the config file instead ? @anoek

**Comment by anoek** [comment]
I would think so. It would be one thing if this was going to be a very common use case, but I don't think it is. It's better to push that logic down stream anyways so if you want to experiment with other conditions other than simply the move number (say based on board size, time settings, or rules), or experiment with fancier logic (like run 3 bots and if 2 of them agree on a move then use that, otherwise pick a random move between them), then you can do that without having to monkey around in gtp2ogs.

**Comment by wonderingabout** [comment]
i see, indeed it makes a lot of sense, i didnt think about that :+1: 

yes, most likely little people will seriously use this (at least in the begining)

so maybe its easier to manage it separately, provided writing such a script out of the js files does not add too much extra work as compared to native implementation (but all in all it will reduce the maintainance of js files of gtp2ogs)

from the little i know, it looks like a good idea @anoek :+1:
