### ISSUE TITLE
add undo support (optionnally enablable with --undo --undoranked --undounranked)

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#158]
@roy7 @Dorus @windo 

i noticed sometimes people misclick against my bot and they resign just after it because of undo impossible

i tested today against gnugo, royalleela and co, and undo is not possible

i noticed the code about undo is here : 

https://github.com/online-go/gtp2ogs/blob/devel/game.js#L34-L38

```
        // TODO: Command line options to allow undo?
        //
        this.socket.on('game/' + game_id + '/undo_requested', (undodata) => {
            this.log("Undo requested", JSON.stringify(undodata, null, 4));
        });
```

but my main motivation for adding undo support is teaching : 
it would be very instructive for players of all levels to roll back a lost game to try other combinations and see how the game would go !! :1st_place_medal: 
and i'll definitely advertise my bot as supporting undo in greeting when this is done :100: 

i'm thinking of adding support for undo optional with `--undo` `--undoranked` `--undounranked`
similar to what was done for `--showboard` in #143 (`--undounranked` seems the wisest one if you ask me, but i'll leave that to botadmin : maybe add a counter for undo `--maxundo` `--maxundoranked` `--maxundounranked` too ?)
also, it may break some bots, so default would be disabled, same as `--showboard`

but i dont know how to support undo

i can write all the documentation, describe and co, as always,
but i need help on the technical way to enable this, which i have no idea how :+1: 

big big thanks

**Comment by windo** [comment]
I believe the tricksy aspects of an undo are:

  1. How to give time for the player to request an undo - if the bot responds in one second then the "request undo" button will already be gone
  2. How to deal with a `genmove` in flight when an undo has been requested - the bot is already making the next move

You may need to add an option to delay making moves (trigger `genmove` from a `setTimeout`?) and when an undo request is granted have to kill and reload the bot unless the bot also supports GTP `undo` (is that standard?)

**Comment by wonderingabout** [comment]
there are indeed 2 aspects to the `undo` support

1- the easier part : connection support
i'll write this part, and it will basically be very similar from the `--showboard` we added not long ago in https://github.com/online-go/gtp2ogs/pull/143 , so basically default would be disabled, and optionally enable if bot supports gtp command `undo` (phoenixgo added it a few weeks ago) AND if bot admin wants to allow undo, the only difference with `showboard` is that we'll have `--undo` `--undoranked` `--undounranked` : bot admin may want to allow it only for unranked games for example, has a great teaching value

2- the harder part : technical support
which is how to actually implement it
since this is beyond my current skills i'll submit a PR with the things i know to do, and i'll leave the technical part for knowledgeable people

@roy7 @Dorus @windo

**Comment by roy7** [comment]
All I can think of is you'd need to kill the bot, do the undo, disconnect from the game, and reconnect so you get a fresh gamedata after the undo is processed.

**Comment by wonderingabout** [comment]
when we want to have a look at adding support for undo again, reminder that we made an attempt in #168

**Comment by Dorus** [comment]
Still a valuable idea.

**Comment by raylu** [comment]
right now when a user requests an undo, the bot effectively freezes and times out: https://online-go.com/game/67929701

```
Sep 19 03:23:04   Game.ts:249          [game 67911272] Opponent played p1
Sep 19 03:23:04   Game.ts:446          [game 67911272] Acquiring main bot instance
Sep 19 03:23:04   Game.ts:456          [bot  1395:1388773] [game 67911272] Acquired bot instance
Sep 19 03:23:04   Game.ts:511          [bot  1395:1388773] Generating move for game 67911272
Sep 19 03:23:04   Game.ts:512          [game 67911272] genmove black
Sep 19 03:23:05   Bot.ts:164           [bot  1395:1388773] MALKOVICH:P1 caused a significant score change: 12.1 points. score lead for black: 0.2
Sep 19 03:23:05   Game.ts:369          [game 67911272] Releasing bot(s)
Sep 19 03:23:05   Game.ts:625          [game 67911272] Min move time was  1500 ms and we only took  852 ms. Waiting  648 ms before sending move
Sep 19 03:23:05   Game.ts:75           [game 67911272] Undo requested 26
Sep 19 03:23:05   Game.ts:581          [game 67911272] Playing f3 { x: 5, y: 16, text: 'f3', resign: false, pass: false }
Sep 19 03:23:38   main.ts:224          Status: playing 0 blitz, 2 live, 0 correspondence games
Sep 19 03:23:38   main.ts:238          Bot status: Main: 2 bots
```
