### ISSUE TITLE
remove apikey from debug, and rethink debug information

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#169]
@roy7 @Dorus @windo 

so while using `--debug` today, i was annoyed to have to remove apikey from screenshots or text log everytime :sob: 

as we are already all aware, apikey is certainly not useful at all to debug most issues, and even if that was the case, there is still security issues with displaying it by default in debug,

maybe using `config.username` instead adresses the same purpose without issue :+1: 

and all in all, maybe its a good opportunity to rethink the debug current display, 
maybe we want to display more useful data

i noticed the code for debug text is here, from 5.3 https://github.com/online-go/gtp2ogs/blob/release-5.3/gtp2ogs.js#L1152-L1159

```
    auth(obj) { /* {{{ */
        obj.apikey = argv.apikey;
        obj.bot_id = this.bot_id;
        obj.player_id = this.bot_id;
        if (this.jwt) {
            obj.jwt = this.jwt;
        }
        return obj;
```

(whenever i dont know where a feature is, i ctrl+f it in old all in one gtp2ogs.js 5.3, very useful)
note : maybe we'd want to have a separate gtp2ogs-6.0-all-in-one-js-stub branch, that would not be functionnal, but allow us to easily find all parts of the code needed in one search

WDYAT ? :smile:

**Comment by roy7** [comment]
I imagine the easy way to do this is on the challenge object we're printing to the debug log, make a copy of it and remove the auth key from the copy, then log the copy instead of the real object.

**Comment by wonderingabout** [comment]
i dont visualize what it would look like, but feel free to commit it, i would be more than happy :+1: 

but i still think we'd also want to rework debug in a bigger picture way, maybe :smile:

**Comment by windo** [comment]
This is probably an overkill for starters but we could plausibly also look for `apikey` object keys in `console.js` and sanitize them before logging.

Fixing the current known code sites that log the `apikey` is much easier of course.

**Comment by wonderingabout** [comment]
theres no rush, so if we want to do something amazing its the right time i think, before master release :1st_place_medal:

**Comment by roy7** [comment]
https://github.com/online-go/gtp2ogs/pull/184

**Comment by roy7** [comment]
Ok added the tiny fix suggested before. @wonderingabout can test it then I'll merge. ;)

**Comment by wonderingabout** [comment]
i think we can close this for now :+1:
