### ISSUE TITLE
Using move alone to trigger genmove

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#19]
@anoek I was thinking when I first noticed the lag between move and active_game that maybe I should just start the bot thinking. I came up with a work around plan, but is it safe to just ignore active_game for games already connected and simply do everything based on move? I was worried what if move comes in, active_game is 10 seconds later, and I submit a move before the active_game arrives. Will the server reject it if it thinks it is still on the prior move? Or can I assume once I get opponent's move event it is safe for me to move immediately?

This would eliminate move/active_game race conditions. I'd just move any time I receive opponent move, and if I get an unexpected gamedata event I can either try to salvage (send any missing move to the bot) or just restart the bot in that case.

**Comment by anoek** [comment]
I believe it should be safe to ignore the active_game events once you've connected to a game (more specifically, once the `game/connect` event has been emitted, you should safely receive gamedata and moves for that game and thus have no further need for the `active_game` events).

So yes, :+1: to doing this

**Comment by roy7** [comment]
Ok fantastic. Maybe that'll be tomorrow's project. It'll make the code cleaner and more understandable too.

**Comment by roy7** [comment]
Ok I put in a big update to the persist branch for your review.
