### ISSUE TITLE
Detect and handle desyncs and illegal moves by alerting or chatting the errors?

### ISSUE THREAD

**Issue by lightvector** [online-go/gtp2ogs#217]
If you are running gtp2ogs and it is playing a game, and you log in as that bot at the same time and make a move in the game such as by accidentally clicking on the board, it appears that the bot and the server can be desynced on the state of the game. This is because both gtp2ogs might never report the move that was exogenously made for the bot's side, and additionally, if the bot was in the middle of a "genmove", then the bot upon finishing the genmove will believe that its own move was made rather than the one that OGS saw due to board click.

This was the case in the following game, where the probably the operator accidentally made a move via the web interface (without realizing this): https://online-go.com/game/21427516

Could gtp2ogs be improved to detect desyncs? If OGS sends the new move down to gtp2ogs the same way it sends the opponent's moves, then the script could detect that this has happened. In such a case, ideally should do something to alert something about the error to make it more visible, such as resigning and/or refusing to continue the game, outputting a chat message that indicates the anomalous state, etc. In the game above, it was *not* obvious to anyone that this had happened.

Additionally, multiple times in the remainder of the game, due to the desync, OGS reported a move that the underlying bot (KataGo) believed was illegal. Based on bot logs that were shared with me, it seems KataGo replied "? illegal move" accordingly with the GTP protocol, but it looks these were also ignored by gtp2ogs.

Could gtp2ogs be improved to alert that this has happened? I think ideal would be to log some error or chat some error message directly to the game chat - basically to make it obvious when the bot believes that game moves are illegal, and that therefore something is seriously wrong, instead of simply continuing the game and hiding that there is any problem.

One could also consider re-starting the bot to replay the moves and see if the bot now recovers to a good state, but I think this is not necessary - if the bug is in the bot, one imagines that often this would not fix it. And it would actually be bad if it worked unless *also* broadcasting or game-chatting or logging the error where it will be prominently noticed. This is because a restart alone, even if it would work to re-sync the bot with OGS, would mask the fact that that the error happened in the first place, hiding the bug in either the bot or gtp2ogs or OGS itself that got it into the state.

**Comment by wonderingabout** [comment]
not directly related to your case, but for information i had 
a similar case of desync with phoenixgo in the past:
https://github.com/online-go/gtp2ogs/issues/190

it was fixed in https://github.com/online-go/gtp2ogs/pull/197

**Comment by Dorus** [comment]
The default behavior for bot crashes is to restart the game a few times and then terminate the game.

We could do the same for desync, restart the bot, send all moves again (default startup behavior), and hope for the best. We do need to keep a counter to prevent endless loops, just like with crashes.

However i don't think it'll be very easy to detect this. We can trust ogs and assume `? illegal move` is always a bot error/desync, but preferable we detect desync problems earlier than that.

The dual input from the bot operator is an interesting one, we should try to reproduce it and see if gtp2ogs receivers any input it could handle better.

**Comment by lightvector** [comment]
I think even detecting it upon illegal move would be a big improvement over simply ignoring errors. A desync is fairly likely to cause an illegal move eventually in the game from at least one of the sides' perspectives, and even if it's too late to restart the bot and fix it in an automated way, simply knowing that it happened is a vast improvement over the current state, where the error is silent. 

Bringing the issue to the attention of a human is almost all the benefit, some super-clever automated handling and restarting is barely worth any more than that and the complexity of it shouldn't stop simply reporting or chatting the error message.

**Comment by Dorus** [comment]
I've checked the code, and actually gto2ogs set the bot in failed state any time it receives an unknown command, or a command starting with a `?` question mark.

Need to investigate why that did not result in a bot restart.
