### ISSUE TITLE
Possibly inaccurate warning message

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#261]
just a reminder from our discord's talk today

@Dorus noticed this issue:

>I was testing the example command line you posted, and it gives me
Warning: You are using --maxperiodslive in combination with --maxperiodsliveunranked and/or --maxperiodsliveranked.
 Use either --maxperiodslive alone, OR --maxperiodsliveunranked with --maxperiodsliveranked.
But don't use the 3 maxperiodslive arguments at the same time.
Warning: You are using --maxperiodtimelive in combination with --maxperiodtimeliveunranked and/or --maxperiodtimeliveranked.
 Use either --maxperiodtimelive alone, OR --maxperiodtimeliveunranked with --maxperiodtimeliveranked.
But don't use the 3 maxperiodtimelive arguments at the same time.
But i checked, and there isn't.

**Comment by Dorus** [comment]
The options i was using:
> --debug --ogspv PhoenixGo --noclock --unrankedonly --minrank 1d --noautohandicapranked --maxhandicap 0 --boardsizes 19 --komis 7.5 --speeds live --maxmaintimelive 600 --maxperiodsliveranked 5 --maxperiodsliveunranked 10 --maxperiodtimeliveranked 60 --maxperiodtimeliveunranked 180

**Comment by wonderingabout** [comment]
i don't know when exactly but this warning does not exist anymore on latest devel

also, in PR #310, we throw an error instead if general and ranked and unranked are all 3 used at the same time, so this can be closed
