### ISSUE TITLE
receiving genmove after double pass

### ISSUE THREAD

**Issue by sanderland** [online-go/gtp2ogs#263]
```
May 09 21:51:34   game.js:499                    [Game 23800365]  Move 294  genmove black
May 09 21:51:34   bot.js:148                     [7030] >>> genmove black
May 09 21:51:34   game.js:499                    [Game 23800365]  Move 294  called genmove in makeMove 23800365
May 09 21:51:34   game.js:499                    [Game 23800365]  Move 294  phase stone removal
````

**Comment by roy7** [comment]
One thing that should have stropped a 2nd genmove beginning once one has already been issued was this change to not ask if the bot is already processing a move:

https://github.com/online-go/gtp2ogs/pull/197

Here was the change related to trying to detect if we get a 2nd gamedata packet that is identical to our current state:

https://github.com/online-go/gtp2ogs/pull/193

**Comment by sanderland** [comment]
this is not a second genmove, that's the other issue, this is the 'stone counting' and 'its your move' being received in quick succession.

**Comment by roy7** [comment]
Sorry I blurred it with the other issue in my mind. :)
