### ISSUE TITLE
Dependencies are apparently broken for npm installs

### ISSUE THREAD

**Issue by anoek** [online-go/gtp2ogs#27]
Performing a `npm install -g gtp2ogs` should be all that is necessary, however something is wrong with dependency installation and thus the current work around is to `npm install optimistsocket.io-client` after they install gtp2ogs. This should not be necessary.

**Comment by wonderingabout** [comment]
should be fixed in #157 

@anoek @roy7 @Dorus

**Comment by roy7** [comment]
The thing was it should have always been working. But I will close this until it happens again.

**Comment by wonderingabout** [comment]
@roy7 

i'm currently updating the gtp2ogs-tutorial while moving to ubuntu 18.04 at the same time

this has been tested to work

i also did `npm audit fix --force` which was also tested to work after that

should i send a new PR for that ?

![node202](https://user-images.githubusercontent.com/38690718/53682134-00d21c00-3cf3-11e9-9880-e42c9f3e6450.png)

**Comment by wonderingabout** [comment]
tested to work ingame : 

![node203d](https://user-images.githubusercontent.com/38690718/53682143-15161900-3cf3-11e9-835a-c0352b40e06a.png)
