### ISSUE TITLE
TODO: redefine time defaults to actually match blitz live corr edge cases

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#288]
currently, when user sends a challenge on OGS, it is sometimes of a different speed type, for example:

- blitz byoyomi maintime 5 minutes is sent as a live challenge
- live byoyomi periodtime 1 hour is sent as a correspondence challenge

this is because the boxes in OGS website allow to input values that are out of range of the blitz live correspondence edge values

to find the accurate edge values, we can do something like --maxmaintimeblitz 1 --maxmaintimelive 999999999 and gradually increase maintime until the challenge is not rejected anymore

this will be the edge value when a blitz challenge is converted to a live challenge

we can also send an issue to @anoek on OGS's github and hope the boxes are fixed to match actualy blitz live corr values

**Comment by Dorus** [comment]
https://github.com/online-go/online-go.com/blob/45b5e2377b2957a7f1a395cf98f9c5db228bfd5a/src/components/TimeControl/util.ts#L499-L502
https://github.com/online-go/online-go.com/blob/45b5e2377b2957a7f1a395cf98f9c5db228bfd5a/src/components/TimeControl/util.ts#L169

**Comment by wonderingabout** [comment]
it seems we also accept unwantingly games canadian 1 hour 55 / 1 stone with these settings (maxmaintime live 3600) , as @Dorus said on discord:

`--debug --persist --boardsizes 9,13,19 --timecontrols byoyomi,canadian,fischer --minperiodtimeblitz 15 --minperiodtimelive 15 --maxperiodtimeblitz 20 --maxperiodtimelive 20 --maxperiodsblitz 10 --maxperiodslive 10 --maxmaintimeblitz 3600 --maxmaintimelive 3600 --maxconnectedgames 1 --maxconnectedgamesperuser 1 --minrankranked 3d --minrankunranked 12k --komisunranked automatic,0.5,6.5,7.5 --komisranked automatic,7.5 --maxhandicapranked 0 --maxhandicapunranked 8 --noautohandicapranked --speeds blitz,live --nopause --ogspv KataGo`

i'll test this on beta later

**Comment by wonderingabout** [comment]
i can confirm this unexpected behaviour @Dorus mentionned

1 hour 55 minutes (6900 seconds) is higher than maxmaintimelive 3600 (1 hour), so we should reject this live challenge
plus the above commandline does not allow correspondence

i'll start to debug this

log below:

```Shell
gtp2ogs version 6.0
--------------------
- For changelog or latest devel updates, please visit https://github.com/online-go/gtp2ogs/tree/devel
Debug status: ON


TESTING WARNINGS:
-------------------------------------------------------
[ SUCCESS ]

May 20 15:38:26   connection.js:659              #  Connecting to https://beta.online-go.com:443
May 20 15:38:26   connection.js:659              #  Connected
May 20 15:38:26   connection.js:659              #  Bot is username:  meta--金毛测试-20b
May 20 15:38:26   connection.js:659              #  Bot is user id:  787
May 20 15:38:42   connection.js:297              # of connected games = 0
May 20 15:38:42   connection.js:659              #  Accepting challenge from metaphysician splurgist :) (13k)  [19x19]  id = 7670
May 20 15:38:42   connection.js:569              POST beta.online-go.com 443 /api/v1/me/challenges/4549/accept {
  apikey: 'hidden',
  bot_id: 787,
  player_id: 787,
  jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJfaWQiOjc4NywiYm90Ijp0cnVlLCJpYXQiOjE1ODk5ODE5MDZ9.TVsKlZ904jVLGCFlwPiCIRc1-34IzCQ6qcigs6zOqOs'
}
May 20 15:38:43   connection.js:659              #  active_game: {"id":7670,"phase":"play","name":"Friendly Match","player_to_move":786,"width":19,"height":19,"move_number":0,"paused":0,"private":false,"black":{"username":"metaphysician splurgist :)","id":786,"rank":17.749501175185603,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":350,"rating":1500,"games_played":0,"volatility":0.06}}},"white":{"username":"meta--金毛测试-20b","id":787,"rank":17.749501175185603,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":350,"rating":1500,"games_played":0,"volatility":0.06}}},"time_per_move":3340}
May 20 15:38:43   game.js:510                    [Game 7670]            Connecting to game.
May 20 15:38:43   game.js:510                    [Game 7670]            gamedata     W   metaphysician splurgist :)  [19x19]    
May 20 15:38:43   game.js:510                    [Game 7670]            clock: {"game_id":7670,"current_player":786,"black_player_id":786,"white_player_id":787,"title":"Friendly Match","last_move":1589981923143,"expiration":1589988823143,"black_time":{"thinking_time":3600,"moves_left":1,"block_time":3300},"white_time":{"thinking_time":3600,"moves_left":1,"block_time":3300},"start_mode":true,"now":1589981923331}
May 20 15:38:43   connection.js:659              #  Deleted notification  787:ce2184a9-ad97-423d-8440-5b053f031d2f
May 20 15:39:41   connection.js:659              #  active_game: {"id":7670,"phase":"play","name":"Friendly Match","player_to_move":787,"width":19,"height":19,"move_number":1,"paused":0,"private":false,"black":{"username":"metaphysician splurgist :)","id":786,"rank":17.749501175185603,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":350,"rating":1500,"games_played":0,"volatility":0.06}}},"white":{"username":"meta--金毛测试-20b","id":787,"rank":17.749501175185603,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":350,"rating":1500,"games_played":0,"volatility":0.06}}},"time_per_move":3340}
May 20 15:39:41   connection.js:659              #  Connected to game 7670 already
May 20 15:39:41   game.js:510                    [Game 7670]            clock: {"game_id":7670,"current_player":787,"black_player_id":786,"white_player_id":787,"title":"Friendly Match","last_move":1589981981149,"expiration":1589988881149,"black_time":{"thinking_time":3600,"moves_left":1,"block_time":3300},"white_time":{"thinking_time":3600,"moves_left":1,"block_time":3300},"now":1589981981150}
May 20 15:39:41   game.js:510                    [Game 7670]            game/7670/move: { game_id: 7670, move_number: 1, move: [ 15, 3, 58149 ] }
May 20 15:39:41   game.js:510                    [Game 7670]  Move 1  Got     q16
May 20 15:39:41   game.js:510                    [Game 7670]  Move 1  makeMove 1 is 1 !== 1 ?
May 20 15:39:41   bot.js:148                     [-1] Starting  ./sai-0.17-cd01531068 --gtp -w ./networks/saiNetwork337.gz --noponder -v 3200 -r 2 --precision half --lagbuffer 1000 --nrsymm --lambda 0.5
May 20 15:39:41   game.js:510                    [Game 7670]  Move 1  Starting new bot process [45282]
May 20 15:39:41   game.js:510                    [Game 7670]  Move 1  State loading for new bot
May 20 15:39:41   bot.js:148                     [45282] >>> boardsize 19
May 20 15:39:41   bot.js:148                     [45282] >>> clear_board
May 20 15:39:41   bot.js:148                     [45282] >>> komi 7.5
May 20 15:39:41   bot.js:148                     [45282] >>> play black q16
May 20 15:39:41   bot.js:148                     [45282] Generating move for game 7670
May 20 15:39:41   game.js:510                    [Game 7670]  Move 1  genmove white
May 20 15:39:41   bot.js:148                     [45282] >>> time_settings 3600 3300 1
May 20 15:39:41   bot.js:148                     [45282] >>> time_left black 3600 0
May 20 15:39:41   bot.js:148                     [45282] >>> time_left white 3594 0
May 20 15:39:41   bot.js:148                     [45282] >>> genmove white

```

**Comment by wonderingabout** [comment]
full notification for this challenge is :

```Shell
{"id":"787:739f2c0d-4ae8-4f0c-9037-79c10ad1d5aa","type":"challenge","player_id":787,"timestamp":1589982486,"read_timestamp":0,"read":0,"aux_delivered":0,"game_id":7671,"challenge_id":4550,"user":{"id":786,"country":"un","username":"metaphysician splurgist :)","icon_url":"https://b0c2ddc39d13e1c0ddad-93a52a5bc9e7cc06050c1a999beb3694.ssl.cf1.rackcdn.com/6c89b5fd5c1965608d50d4f9b4829078-32.png","ratings":{"overall":{"deviation":350,"rating":1500,"games_played":0,"volatility":0.06}},"ui_class":"provisional","professional":false,"rating":"1273.117","ranking":17.749501175185603},"rules":"chinese","ranked":false,"aga_rated":false,"disable_analysis":false,"handicap":0,"komi":null,"time_control":{"system":"canadian","time_control":"canadian","speed":"live","pause_on_weekends":false,"main_time":3600,"period_time":3300,"stones_per_period":1},"challenger_color":"automatic","width":19,"height":19}
```

so 1 hour 55 minutes (6900 seconds) is detected by ogs server as maintime 3600, so we allow the game,
i am testing if maxmaintime 3500 rejects the game as expected

**Comment by wonderingabout** [comment]
update : there is no issue with gtp2ogs!!!

live canadian 1 hour 55 minutes does not exist on the ogs grid,

![1 hour 55 minutes v1](https://user-images.githubusercontent.com/38690718/82455653-77536900-9ab3-11ea-8671-2b6939bef5a3.png)

so what @Dorus did was to do 1 hour maintime 55 minutes periodtime

`{"id":"787:739f2c0d-4ae8-4f0c-9037-79c10ad1d5aa","type":"challenge","player_id":787,"timestamp":1589982486,"read_timestamp":0,"read":0,"aux_delivered":0,"game_id":7671,"challenge_id":4550,"user":{"id":786,"country":"un","username":"metaphysician splurgist :)","icon_url":"https://b0c2ddc39d13e1c0ddad-93a52a5bc9e7cc06050c1a999beb3694.ssl.cf1.rackcdn.com/6c89b5fd5c1965608d50d4f9b4829078-32.png","ratings":{"overall":{"deviation":350,"rating":1500,"games_played":0,"volatility":0.06}},"ui_class":"provisional","professional":false,"rating":"1273.117","ranking":17.749501175185603},"rules":"chinese","ranked":false,"aga_rated":false,"disable_analysis":false,"handicap":0,"komi":null,"time_control":{"system":"canadian","time_control":"canadian","speed":"live","pause_on_weekends":false,"main_time":3600,"period_time":3300,"stones_per_period":1},"challenger_color":"automatic","width":19,"height":19}`

i confirmed and 1 hour 50 minutes 1 stone is indeed rejected

`{"id":"787:5cac8460-d567-4ae0-97a3-73d8df477d80","type":"challenge","player_id":787,"timestamp":1589982990,"read_timestamp":0,"read":0,"aux_delivered":0,"game_id":7672,"challenge_id":4551,"user":{"id":786,"country":"un","username":"metaphysician splurgist :)","icon_url":"https://b0c2ddc39d13e1c0ddad-93a52a5bc9e7cc06050c1a999beb3694.ssl.cf1.rackcdn.com/6c89b5fd5c1965608d50d4f9b4829078-32.png","ratings":{"overall":{"deviation":350,"rating":1500,"games_played":0,"volatility":0.06}},"ui_class":"provisional","professional":false,"rating":"1273.117","ranking":17.749501175185603},"rules":"chinese","ranked":false,"aga_rated":false,"disable_analysis":false,"handicap":0,"komi":null,"time_control":{"system":"canadian","time_control":"canadian","speed":"live","pause_on_weekends":false,"main_time":6600,"period_time":60,"stones_per_period":1},"challenger_color":"automatic","width":19,"height":19}
May 20 15:56:30   connection.js:297              # of connected games = 0
May 20 15:56:30   connection.js:661              #  1 hours 50 minutes is above Maximum Main Time for live games in canadian 1 hours
May 20 15:56:30   connection.js:661              #  Rejecting challenge from metaphysician splurgist :) (13k)  [19x19]  id = 7672
May 20 15:56:30   connection.js:571              POST beta.online-go.com 443 /api/v1/me/challenges/4551 {
  delete: true,
  message: 'Maximum Main Time for live games in canadian is 1 hours, please reduce Main Time.',
  apikey: 'hidden',
  bot_id: 787,
  player_id: 787,
  jwt:
}`

so this issue is solved
