### ISSUE TITLE
Make it optional for bots to appear in Vs Computer drop down?

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#29]
As more people ask about setting up bots, just to play around with briefly I think, it might be nice for them not to appear in the Vs Computer list as a toggle the operator can set? Maybe they just want to run a program on OGS but not have it accept challenges from the public. My concern is if someone is testing or just wants to have a bot play a specific game, when they stop the bot any other random public challenges will all time out and provide a bad experience to the unsuspecting human opponents?

**Comment by TokumotoK** [comment]
Please allow me to state my take on this issue.  Accepting challenges from the public is (at least should be) a prerequisite to holding a bot account on OGS production server.  Also, it should be a condition to holding a bot account to keep the bot online more or less all the time.  I feel the mods have been too lenient on these points in creating bot accounts.

If someone wants to test a bot, it should be done on the test server, not the production.

**Comment by anoek** [comment]
Implemented in #63
