### ISSUE TITLE
gamedata.auto_score is inconsistently sent by server: "Killing bot because of gamedata change after bot was started"

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#300]
it's nice that we fixed the clock.now inconsistency in #296 , but server has other tricks under its hat

I spotted an `auto_score` property inconsistently sent, causing a change of gamedata bot kill

This happened only once and auto-fixed after bot new instance

# [Download Full Log (277 kB)](https://drive.google.com/file/d/162UmnePX4xFjMAhohYdtK6NWkVKHrJBS/view?usp=sharing)

analyzing the 2 gamedatas makes the `auto_score` extra property inconsistently sent obvious, at lines 46 and 122

![gamedata other difference](https://user-images.githubusercontent.com/38690718/82759360-4fcf0a00-9ded-11ea-8f45-430c0f400df7.png)

finally i want to say even though in the last few hours ogs server has been very unstable, being up and down regularly, our gtp2ogs now reacts very reliably :100:

**Comment by roy7** [comment]
https://github.com/online-go/gtp2ogs/pull/301

**Comment by wonderingabout** [comment]
tested to work, game works end to end :+1:
