### ISSUE TITLE
run a mini gtp test game before playing against other users on OGS (to fix crashing bot due to wrong bot command)

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#315]
while writing the botcommand for my new 9b sai, i made a typo in the network name which made gtp2ogs crashloop during a game, had to force exit the process with ctrl+c

logs can be downloaded here:
https://drive.google.com/file/d/1HiyWHD0MWNDxqLd1lEqxgcX8oZzW7G9u/view?usp=sharing, https://drive.google.com/file/d/1rKV1axouyHNSmjPR0H_8vlcqbuqC4EY3/view?usp=sharing

ideally we would want to check with a quick test game in gtp mode that our bot communicates well with the AI in a local game, else throw an error before starting connection to the server

**Comment by wonderingabout** [comment]
@Dorus mentionned having the same issue with his bot too due to wrong bot command (unexisting folder due to typo)

https://pastebin.com/e1Jsn8Qk
https://pastebin.com/ZLQcttwX

so we'd want to make sure our bot works before playing games on OGS

**Comment by wonderingabout** [comment]
initial intent of this was to proactively detect mistypes in bot command, but it could also be used on a wider extent, to detect if bot is set up fine and does not crash

for example

https://online-go.com/game/24669608
https://online-go.com/game/24669700

some bots are online but crash due to a wrong setting
it would be cool if we can throw an error after a basic gtp testing at specified --boardsizes and --komis

(`genmove`, play a few moves, `pass`, `resign`), before connecting on ogs, first testing these locally

**Comment by Dorus** [comment]
This would still be useful.

**Comment by anoek** [comment]
I think this is beyond the scope of gtp2ogs, if it's an ongoing problem during development, I would recommend the operator test the command before configuring gtp2ogs
