### ISSUE TITLE
drop --fakerank and fetch bot rank from any gamedata we have

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#325]
as @sanderland suggested on discord, we can update bot rank at every gamedata we get in a game

until we get any gamedata (start any game) we would not check
also, updating botrank from latest gamedata is an instant operation which is not costly

current implementation of --fakerank is too complicated, but also inaccurate, as fake rank is a rank estimation from bot admin, but bot rank can change anytime during the session, in an unpredictable direction

new option would be something like `--detectautohandicapstones` with their ranked unranked equivalents

**Comment by sanderland** [comment]
I would suggest removing fakerank, and making this detect standard/always on.

**Comment by wonderingabout** [comment]
i guess we could already remove fakerank as a starter, since this is easy we can do it in a separate pr

then for this feature to be always this would mean to use a negative boolean (ex: `--noautohandicapstonesdetection`)

**Comment by sanderland** [comment]
> then for this feature to be always this would mean to use a negative boolean (ex: `--noautohandicapstonesdetection`)

Think about it, who would use that, and why? 
I think it's best to think about the useful cases (auto handicap only / possibly with limit, manually set limit)

**Comment by wonderingabout** [comment]
oh actually you're right, as long as this feature is working as intended every bot admin would want to use it
also, if it doesnt work, not using it is not a fix either

> I think it's best to think about the useful cases (auto handicap only / possibly with limit, manually set limit)
i should practice that more :sweat_smile:

**Comment by wonderingabout** [comment]
continues in #349
