### ISSUE TITLE
Client got suspended

### ISSUE THREAD

**Issue by breakwa11** [online-go/gtp2ogs#337]
Sometimes got this error message
```
Jun 29 22:06:06 !!!!! connection.js:706              #  520 - <html>
<head><title>520 Origin Error</title></head>
<body bgcolor="white">
<center><h1>520 Origin Error</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

Jun 29 22:06:06 !!!!! connection.js:707              Error
    at conn_log (....\connection.js:707:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

then, the client do nothing until the game timeout.

**Comment by wonderingabout** [comment]
Hi, thanks for asking the question,

@Dorus had the same error 520 last month due to a server instability that day
https://discord.com/channels/417022162348802048/530479098238337025/712767003626307734

Is your issue fixed after restarting gtp2ogs, and do you have a longer log ?

**Comment by breakwa11** [comment]
Sure, restarting client would fixed the problem.

Sorry, I did not keep a longer log. I will keep it next

**Comment by wonderingabout** [comment]
All good,

it is convenient to log in a file if you have an unexpected crash or lose too early console output, also it is very helpful for debugging
you can log files with `--logfile`
https://github.com/online-go/gtp2ogs/blob/devel/docs/OPTIONS-LIST.md#logfile

it is also a good idea to start gtp2ogs from a specific folder used for logging, to avoid filling your main gtp2ogs directory

for example:

`cd ~/gtp2ogs_logs && node ~/gtp2ogs/gtp2ogs.js --apikey vizq1cqz981qz1qz1cqz7fqz9f1qz1zq9 --username someUser --debug --logfile --boardsizes 19 -- ~/sai/build/sai-0.17-d2c82fc0 --gtp -w ~/networks/sai/9b/e1eab1d6_1913000.gz --noponder -v 3500 --symm -r -1 --lambda 1.0 --mu 0`

will save your log file for current session in `~/gtp2ogs_logs/`

hope this helps :+1:

**Comment by breakwa11** [comment]
After I add `--logfile`
```
Jul 04 00:54:40 !!!!! gtp2ogs.js:21                  ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number. Received undefined
    at Object.write (fs.js:611:3)
    at ...\console.js:32:16
    at FSReqCallback.oncomplete (fs.js:155:23)
```

My nodejs version is v12.18.1-x64 on windows

**Comment by wonderingabout** [comment]
this should be a syntax error

can you send your full gtp2ogs command (remove your apikey because it is a password of your bot account)

for example my ful gtp2ogs command is (apikey hidden) :

`cd ~/gtp2ogs_logs && node ~/gtp2ogs/gtp2ogs.js --apikey testapikeyfake --username meta-βακα-epic-SAI --debug --maxconnectedgamesperuser 1 --maxconnectedgames 2 --boardsizes 19 --komis all --noclock --persist --nopause --minrank 10k --timecontrols fischer,byoyomi --speeds blitz,live --minperiodtimeblitz 5 --minmaintimelive 60 --maxmaintimelive 1200 --minperiodtimelive 30 --maxperiodtimelive 180 --maxperiodslive 5 --greeting "hi, this SAI http://sai.unich.it/ bot plays with an omoshiroi style, have fun!" --greetingbotcommand --farewell "thanks for the game, hope you enjoyed!" --ogspv Sai --logfile --rejectnewthreshold 22:30 -- ~/sai/build/sai-0.17-d2c82fc0 --gtp -w ~/networks/sai/12b/368.gz --noponder -v 3500 --symm -r -1 --lambda 1.0 --mu 0`

also what version of gtp2ogs are you using?
the ability to not provide a name and use default name was a recent addition in https://github.com/online-go/gtp2ogs/commit/7c30891879410c86ef7286d50ffb1150887e5bb9 22nd may 2020, if your gtp2ogs version is older than that you need to update to a more recent version

**Comment by breakwa11** [comment]
gtp2org version 6.0.0

`node gtp2ogs.js --username botname --apikey key --debug --noclock --noautohandicap --nopause --komis 7.5,6.5,automatic --timecontrols fischer,byoyomi,canadian,simple --minperiodtimelive 20 --corrqueue --maxconnectedgamesperuser 1 --speeds live --persist --logfile --boardsizes 19 --maxconnectedgames 5 --minrankunranked 20k --maxhandicapranked 0 --maxhandicapunranked 9 --minhandicapunranked 2 -- %botcmd%`

**Comment by roy7** [comment]
I always put a filename after --logfile myself, but I guess we added support so filename is optional. gtp2ogs 6.0.1 is out now and may include that change if it wasn't in 6.0.0.

**Comment by wonderingabout** [comment]
syntax is fine

i dont know much about the fs module, maybe @Dorus has an idea about this issue

for now as a temporary workaround you can manually add a filename, it should work, for example `--logfile myLogFile`

**Comment by breakwa11** [comment]
I got the answer

The file name as `gtp2ogs_logfile_2020-07-10T01:55:21.019Z`

The `:` is illegal on windows

**Comment by wonderingabout** [comment]
great!!

i pushed a PR for a fix in https://github.com/online-go/gtp2ogs/pull/354#issue-447307229

i tested on my linux machine as shown in screenshots, could you confirm it fixes the issue on your machine too?

**Comment by breakwa11** [comment]
I will test it later

I found another case

```
Jul 11 15:12:10   connection.js:709              #  active_game: {"id":25343372,"phase":"play","name":"Friendly Match","player_to_move":a,"width":19,"height":19,"move_number":0,"paused":0,"private":true,"black":{"username":"A","id":a,"rank":17.749501175185603,"professional":false,"accepted":false,"ratings":{"overall":{"rating":1500,"deviation":350,"volatility":0.06}}},"white":{"username":"B","id":b,"rank":25.53595288451076,"professional":false,"accepted":false,"ratings":{"overall":{"rating":1924.4333539194258,"deviation":67.0462727521707,"volatility":0.06132766269285773}}},"time_per_move":31}
Jul 11 15:12:10   game.js:523                    [Game 25343372]            Connecting to game.
Jul 11 15:12:10   connection.js:709              #  Deleted notification  b:bc76xxx
Jul 11 15:12:11   game.js:523                    [Game 25343372]            No gamedata after 1s, reqesting again
Jul 11 15:12:11   game.js:523                    [Game 25343372]            Unable to react correctly - re-connect to trigger action based on game state.
Jul 11 15:12:13   connection.js:709              #  active_game: {"id":25343372,"phase":"play","name":"Friendly Match","player_to_move":b,"width":19,"height":19,"move_number":1,"paused":0,"private":true,"black":{"username":"A","id":a,"rank":17.749501175185603,"professional":false,"accepted":false,"ratings":{"overall":{"rating":1500,"deviation":350,"volatility":0.06}}},"white":{"username":"B","id":b,"rank":25.53595288451076,"professional":false,"accepted":false,"ratings":{"overall":{"rating":1924.4333539194258,"deviation":67.0462727521707,"volatility":0.06132766269285773}}},"time_per_move":31}
Jul 11 15:12:13   connection.js:709              #  Connected to game 25343372 already
Jul 11 15:13:13   connection.js:709              #  active_game: {"id":25343372,"phase":"finished","name":"Friendly Match","player_to_move":b,"width":19,"height":19,"move_number":1,"paused":0,"private":true,"black":{"username":"A","id":a,"rank":17.749501175185603,"professional":false,"accepted":false,"ratings":{"overall":{"rating":1500,"deviation":350,"volatility":0.06}}},"white":{"username":"B","id":b,"rank":25.53595288451076,"professional":false,"accepted":false,"ratings":{"overall":{"rating":1924.4333539194258,"deviation":67.0462727521707,"volatility":0.06132766269285773}}},"time_per_move":31}
Jul 11 15:13:13   connection.js:709              #  25343372 active_game phase === finished
```

All new games show `No gamedata after 1s, reqesting again`

**Comment by wonderingabout** [comment]
this could be normal behaviour of OGS server to sometimes be slow to send gamedata packet for a new game

we may also flag as errors errors in console "ERROR:" to easily find them in logs

@Dorus and @roy7 know these things better than me, hope they can help 😉
