### ISSUE TITLE
--hidden does not hide bot

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#364]
issue noticed by jbx2010 on discord

![hidden does not work devel](https://user-images.githubusercontent.com/38690718/88451607-36335880-ce58-11ea-87c3-bfec549ef785.png)

i could reproduce the issue both with latest devel, and with an old branch (https://github.com/wonderingabout/gtp2ogs/tree/fix-nohidden) that i tested in the past to successfully hide bot if --rejectnew or --hidden is set

so this is not caused by any recent change of gtp2ogs, but may be related to an OGS server change

**Comment by wonderingabout** [comment]
this is when we tested --hidden or --rejectnew to successfully hide our bot

https://github.com/online-go/gtp2ogs/pull/303
https://github.com/online-go/gtp2ogs/pull/304

**Comment by Dorus** [comment]
This is probably https://github.com/online-go/online-go.com/issues/1209 and not any error on gtp2ogs side.

**Comment by wonderingabout** [comment]
yes, there seems to be no reason why same code wouldnt work anymore outside of a non-gtp2ogs change

**Comment by anoek** [comment]
Yeah I broke things on ogs, sorry about that. Should be fixed up now.

**Comment by wonderingabout** [comment]
all good, glad this is fixed 💯
