### ISSUE TITLE
[FeatReq] add an option to use a config file instead of writing all args in CLI

### ISSUE THREAD

**Issue by PabloLION** [online-go/gtp2ogs#383]
## Context
As current options can only be inputed as CLI args and the number of options seems to grow,

> In gtp2ogs, options need to be inputted as command-line arguments.
> The number of options (and of bot arguments) is free, use the ones you want.
Origin: https://github.com/online-go/gtp2ogs/blob/devel/docs/OPTIONS-LIST.md

Adding a file to store it can be convenient for

1. fist-time setup
2. TS typing
3. profile different default config (like a `katago_config.ts` for katago users)
4. switching between configs
5. handling space character (` `) in username

## Suggestion

We can use either dot-env, a json file, or a TS/JS file to store all the configs (like [ESLint Config](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new)). I'd prefer to first support TS file to give user a clue without adding JSON-Schema.

The file would be like
```ts
interface OGS-Config {
beta: boolean;
host: string;
port: number;
apiKey: string;
maxconnectedgames?: number;
debug?: boolean;
// ...
}

export default const config = {
host: "online-go.com",
port: 443,
beta: false,
apiKey: "XXX_SOME_API_KEY_XXX"
}
```

To adopt this config we need to

1. add a `--configFile path/to/config.ts` or use a default path.
2.  update the function `updateFromArgv`
    https://github.com/online-go/gtp2ogs/blob/d275c684d68630a1311fca09a6ca8a7f4f664bad/src/config.ts#L14

## Side-effect

1. more readability for `updateFromArgv`
2. easier type-checking and more ts adoption
3. more structural config
6. we can have a constant `DEFAULT/CONFIG`/`BASE_CONFIG` and split the default/suggested config from building a customised config. 

## Alternative

Create an executable `run.sh` in repo root like below (sample args from [tutorial-3A5](https://github.com/wonderingabout/gtp2ogs-tutorial/blob/master/docs/3A5-linux-run-gtp2ogs-js-beta.md)

```sh
node ~/gtp2ogs-node/node_modules/gtp2ogs/gtp2ogs.js \
--beta \
--apikey 53e4288597ab04c591dffikz4se8u6v1y2z8tty7 \
--username meta--金毛测试-20b \
--debug \
--persist \
--noclock \
-- \
/home/amd2020/PhoenixGo/bazel-bin/mcts/mcts_main \
--gtp \
--config_path=/home/amd2020/PhoenixGo/etc/mcts_1gpu.conf
```

**Comment by Dorus** [comment]
Lets not get carried away with mixing ts types with config documentation. One is for programmers to check if there code is correct, and uses tooling. The other is for end users that generally dont use tooling, so you would have to document this stuff yourself.

I did a quick writeup to add the config module to gtp2ogs. Fairly straightforwards, but i also ran into some caveats. The config module seems to load the config regardless of calling the config methods, thus my fork is now stuck with a "WARNING: No configurations found in configuration directory:" for non-config users. I was also unable to read all config settings from the root object, would need to dig into the config package to find out if that's something they support. For now i've decided to wrap all config settings in a config root object. Also documentation is still lacking.

My (for now unfished) code is here:

https://github.com/online-go/gtp2ogs/compare/devel...Dorus:gtp2ogs:config-file?expand=1

**Comment by Dorus** [comment]
> handling space character ( ) in username

I'm pretty sure this is already supported. Don't forget to put the name in quotes.
