### ISSUE TITLE
obanSocket error unable to verify the first certificate

### ISSUE THREAD

**Issue by Dorus** [online-go/gtp2ogs#418]
Since yesterday my bots are crashing with the error

```
[33mApr 17 18:26:02   main.ts:143          Disconnected from server[39m
[32mApr 17 18:26:02   GobanSocket.ts:289   GobanSocket reconnecting in 50ms[39m
[31m[1mApr 17 18:26:02 ! GobanSocket.ts:206   GobanSocket error unable to verify the first certificate[22m[39m
[33mApr 17 18:26:02   GobanSocket.ts:217   GobanSocket closed with code 1006: Abnormal Closure[39m
[33mApr 17 18:26:02   main.ts:143          Disconnected from server[39m
[32mApr 17 18:26:02   GobanSocket.ts:289   GobanSocket reconnecting in 258ms[39m
[31m[1mApr 17 18:26:03 ! GobanSocket.ts:206   GobanSocket error unable to verify the first certificate[22m[39m
[33mApr 17 18:26:03   GobanSocket.ts:217   GobanSocket closed with code 1006: Abnormal Closure[39m
[33mApr 17 18:26:03   main.ts:143          Disconnected from server[39m
```

I'm not sure what causes this, there do seem to be other bots online.

**Comment by raylu** [comment]
perhaps you have some old CAs? what does this say?

    openssl s_client -connect online-go.com:443 < /dev/null | openssl x509 -noout -text

I get this cert https://crt.sh/?id=12255514776
though it looks like a newer cert was issued 6 days later https://crt.sh/?id=12326863795
they were both issued in march, though, so I don't think anything has changed recently

**Comment by Dorus** [comment]
Do you have a windows equivalent of that command at hand?

**Comment by raylu** [comment]
ah... on windows, node isn't patched to use the system's CA store https://github.com/nodejs/node/issues/4175. so you might just need to upgrade node? unless you're using the brotli-built executables, in which case the project needs to upgrade something

**Comment by Dorus** [comment]
Oh!

I was using a very old node
```
node -v
v18.13.0
```

Updated to the latest, 21.7.3, still the same error

**Comment by Dorus** [comment]
Not sure what changed but it all works again.
