### ISSUE TITLE
Auto scoring fail can lead to abuse

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#43]
Have had this happen a number of times vs RoyalLeela, if the auto score accept fails, the human player changes the board to give themself a win. The bot doesn't argue the score, and so it is accepted via timeout.

An idea since not all bots can provide lists of dead stones to try and handle scoring directly is to accept the score the moment it first appears, but reject score any time human manually makes a change. So if you want bot to accept a score after both sides pass, you can't manually change anything on the board. That should at least enforce the auto score initial results?

If the server auto score works, then that's that, this would be a failsafe on the gtp2ogs side in case server doesn't enforce auto scoring.

This is the sort of thing I'm trying to avoid:

https://online-go.com/game/8514311
https://online-go.com/game/8530265
https://online-go.com/game/8518362

etc

**Comment by roy7** [comment]
Some recent DarkGo abuse too. No need to list all the games, but they guy changed 10 ranked results to all be completely his color board:

https://online-go.com/player/433387/

**Comment by windo** [comment]
Is this supposed to be fixed now by server-side changes?

**Comment by roy7** [comment]
Yes because the server automatically does scoring, humans can't change the scoring on-board.
