### ISSUE TITLE
"Challenge does not exist"

### ISSUE THREAD

**Issue by TokumotoK** [online-go/gtp2ogs#52]
When I am logged in via browser as Bifron while Bifron is online, and if Bifron rejects a challenge (via auth() which results in "Challenge does not exist"), Bifron starts receiving a Challenge Notification once every 3 to 10 seconds on the same non-existing challenge until I manually reject the challenge on the browser.

As I felt this is a server-side issue, I discussed with anoek, who suggested to log it here so that roy7 might come up with a solution or have some idea on the issue.  Content of the notification includes 'read' flag of '0', 'read_timestamp' of '0'

**Comment by TokumotoK** [comment]
I've found this problem happens even when I'm not logged in as Bifron via browser.
Bifron logged:
gtp2ogsbif3.js:1580 # Carpinus wanted speed correspondence, not in: live
gtp2ogsbif3.js:1580 # Carpinus ranking too low: 14.9802532377569 (node:10084)
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): [object Object]

And the above mentioned Challenge Notification every 10 seconds problem that result in "Challenge does not exist" starts.

The log was obtained when I replaced the
.then(ignore).catch(conn_log);
part in the challenge rejection to:
try {del(api1('me/challenges/' + notification.challenge_id), this.auth({ }));}
 catch(err){ ...bleh... }

Further, I found that this problem is not unique to Bifron (which uses the gtp dialect version gtp2ogs) but also happens on Kugutsu and Nicaso (which use the unmodified newest roy7 version).  Just the frequency is different as Bifron rejects far more challenges than the other two bots.

**Comment by TokumotoK** [comment]
I am not getting this symptom any longer.  It seems some server-side update corrected the unhandled promise rejection issue.
Please close this ticket.

**Comment by TokumotoK** [comment]
Nicaso logged the following while running ae4c258:

Oct 02 16:44:06   [Game 14665768]  Move 170  gamedata     W   RyanJiang  [19x19]
Oct 02 16:44:06   [Game 14665768]  Move 170  Game over.   Result: W+R      W
Oct 02 16:44:06   [15052] Stopping bot
Oct 02 16:44:07   [Game 14665768]  Move 170  Disconnecting from game.
Oct 02 17:16:10   #  board width 13 not an allowed size, rejecting challenge
Oct 02 17:16:10   #  Rejecting challenge from JuWei (6k)  [13x13]  id = 14666036
Oct 02 17:16:46   #  board width 13 not an allowed size, rejecting challenge
Oct 02 17:16:46   #  Rejecting challenge from JuWei (6k)  [13x13]  id = 14666043
Oct 02 17:16:46   #  board width 13 not an allowed size, rejecting challenge
Oct 02 17:16:46   #  Rejecting challenge from JuWei (6k)  [13x13]  id = 14666043
Oct 02 17:16:46 !!!!! #  404 - {"error":"Challenge does not exist"}
Oct 02 17:16:46 !!!!! Error
    at conn_log (C:\cygwin64\usr\src\gtp2ogs-devel\gtp2ogsae4c258.js:1820:23)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by wonderingabout** [comment]
i'm having the same issue here too :+1:  @TokumotoK @roy7 

![challenge does not exist loop](https://user-images.githubusercontent.com/38690718/51412093-bba2c200-1b6a-11e9-9c8c-d4adb5cf331b.png)
![challenge loop2](https://user-images.githubusercontent.com/38690718/51412092-bba2c200-1b6a-11e9-885e-f73e2024def7.png)

some undeleted challenge keeps popping on loop

at one moment i thought the player was motivated to play against my bot lol

but actually its just the challenge didnt get deleted

**Comment by wonderingabout** [comment]
also the challenge doesnt appear in https://online-go.com/overview, you can see it only if you scroll notifications on top right

**Comment by wonderingabout** [comment]
getting this error today again : 

![challenge error3](https://user-images.githubusercontent.com/38690718/51430009-1abd1100-1c15-11e9-91fe-565aacc59d1f.png)

this time however it doesnt loop because the challenge is not on notifications list on top right (i guess the bot deleted it this time)

**Comment by roy7** [comment]
I'm assuming this was addressed by https://github.com/online-go/gtp2ogs/pull/267
