### ISSUE TITLE
 Cannot read property 'game_id' of null

### ISSUE THREAD

**Issue by TokumotoK** [online-go/gtp2ogs#55]
I like the --greeting and --farewell, but Kugutsu, Nicaso and Bifron all disconnected from OGS after they started using the Whitespace version as follows:

/usr/src/gtp2ogs-devel/gtp2ogs.js:876
        if (argv.farewell && this.state.game_id != null) {
                                       ^

TypeError: Cannot read property 'game_id' of null
    at Game.disconnect (/usr/src/gtp2ogs-devel/gtp2ogs.js:876:40)
    at Connection.disconnectFromGame (/usr/src/gtp2ogs-devel/gtp2ogs.js:1116:43)

All 3 bots had exactly the same Error.

I am replacing the line 876:
-        if (argv.farewell && this.state.game_id != null) {
with
+       if (argv.farewell && this.state.game_id) {

and will observe how it runs.

**Comment by TokumotoK** [comment]
Got the same Error.  Trying:
  if (argv.farewell && this.game_id) {

**Comment by roy7** [comment]
Test for this.state

**Comment by roy7** [comment]
@willemhendriks

**Comment by roy7** [comment]
The problem is the game state is already gone so trying to access something in this.state will fail. He probably meant this.state != null.

**Comment by TokumotoK** [comment]
Thanks.
but line 897 also says  'game_id': this.state.game_id,
so that can't be what he meant, and I don't see how the test for "game state must be gone"
should be necessary.
I am trying line 876:
-- if (argv.farewell && this.state.game_id != null) {
++ if (argv.farewell && this.game_id) {
line 898:
-- 'game_id': this.state.game_id,
++ 'game_id': this.game_id,
line 908:
-- 'game_id': this.state.game_id,
++ 'game_id': this.game_id,
(line numbers may be off by a few)

and observe how it runs.

**Comment by roy7** [comment]
Yes I see what you mean. I was just trying to reply quickly off my phone. :)

**Comment by roy7** [comment]
sendChat on line 908 also uses this.state.game_id like you noticed. Hmm. I can't explain why there's a mix of this.game_id vs this.state.game_id throughout the code.

If your tests also work fine maybe we'll move to that. A simple way to avoid the error message is just

if (argv.farewell && this.state && this.state.game_id != null) {

Although I don't know how we could have a this.state and the state not have a game_id.

**Comment by roy7** [comment]
I don't use farewell messages so it hasn't crashed my bots, I thought Kungfu Panda was using it on his bots though and it worked. :(

**Comment by roy7** [comment]
Hmm, I know the greeting works since my bot uses it, but I wonder how this sendChat( ) call works with the move number missing.

**Comment by willemhendriks** [comment]
Hi Guys,

I wrongly implemented this farewell - the original code from Mr Ping is as such:
```
disconnect() { /* {{{ */
        this.log("Disconnecting from game #", this.game_id);
        this.disconnect_fo_real();
    }; /* }}} */
    disconnect_fo_real() { /* {{{ */
        if( this.state != null ){
                if( this.state.game_id != null ){
                        this.sendChat("BOT MESSAGE - Thank you for this great game!", "discussion");
                        var result_cmd = require('child_process').execSync('python parse_gtp_output.py ' + this.state.game_id).toString();
                        var analyze_lines = result_cmd.split("\n");
                        var arrayLength = analyze_lines.length;
                        for (var i = 0; i < arrayLength; i++) {
                                this.sendChat("BOT MESSAGE: " + analyze_lines[i], "discussion");
                        }
                }
        }
```

disconnect_fo_real() is not present in current master.

Probably key is to perform both checks:
```
if( this.state != null ){
                if( this.state.game_id != null )
```

**Comment by TokumotoK** [comment]
It's been a few hours since I replaced 'this.state.game_id' with 'this.game_id' at the 3 locations mentioned above.  
1. gtp2ogs.js on all 3 bots have been working fine without any Errors.
2. Greeting works fine without the move number.  Chat window shows just 'Move' without any number following it, then the message.
3. Farewell works, but the bots sends farewell message twice.  Chat window shows just 'Move' and the same message twice.

I'll leave it to you guys for the best solution.

**Comment by TokumotoK** [comment]
I just noticed Nicaso sent Farewell message 16 times in https://online-go.com/game/10877203

**Comment by willemhendriks** [comment]
Weird, the bot has trouble to say goodbye, maybe they do have feelings

**Comment by roy7** [comment]
I was concerned about that. The issue is the server will, for a long time after a match is done, still send it in the response when the client asks for a list of matches. Then it'll see the match is already done, and so it'll disconnect() from it. We could perhaps try to catch that up front and not even set the game state up if it's already over with. Then we don't need to disconnect() from it again?

**Comment by roy7** [comment]
Basically when active_game arrives,

let game = this.connectToGame(gamedata.id);

could be conditional that gamedata.phase != "finished"

**Comment by roy7** [comment]
Ok I did a simple fix https://github.com/online-go/gtp2ogs/pull/57. Please test it out @TokumotoK ?

**Comment by TokumotoK** [comment]
haha, yea, maybe they do

**Comment by TokumotoK** [comment]
roy7, thanks.  I will

**Comment by TokumotoK** [comment]
The first game Kugutsu finished using #57 https://online-go.com/game/11220176
Seems fine.
The game was started with the mods I applied to the Whitespace version, so will see how #57 runs when it starts and finishes a game for a while

**Comment by TokumotoK** [comment]
The first game Kugutsu started and finished with #57 
https://online-go.com/game/11220390
Works fine.

Will observe how stable #57 runs

**Comment by TokumotoK** [comment]
As I understand it, #57 checks if this.state is still there, and if there is, then sends the Farewell message.
My mods on the other hand don't care if the state on the finished game is still there or not, and uses this.game_id for sending Farewell message.  Is the former a better solution?

May be the point is moot as I totally agree solving issue #58 is the proper solution, but this "send farewell message ONLY WHEN there still is the game state alive" might carry over, and there might be a chance my mods will actually be better?

**Comment by roy7** [comment]
I was trying to solve the problem by changing as little code as possible, since I don't recall reasons why there is a game.state.game_id and a game.game_id. Plus @willemhendriks intended to check for game.state != null and just left it out in error.

**Comment by TokumotoK** [comment]
oh I see.  thanks
