### ISSUE TITLE
Don't connect to finished games

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#58]
See: https://github.com/online-go/gtp2ogs/issues/55#issuecomment-356322452

Since we connect to every active_game, even finished ones, we end up connecting and disconnect()'ing over and over until server stops telling us about that game, which makes the farewell code send a farewell every time we disconnect().

If we check for game status when active_game comes in, we could simply not connect to a finished game in the first place. Then the disconnect() later wouldn't be needed since it wouldn't be in the connected_games list.

**Comment by windo** [comment]
I think this is already the case, should close?

**Comment by roy7** [comment]
If you've never noticed this happening go ahead and close. I just thought sometimes I'd see in my logs old active_games arrive on finished games but we'd connect/disconnect to it even though it's already finished.

**Comment by wonderingabout** [comment]
is this related to #159 ?

**Comment by wonderingabout** [comment]
can this be closed now that #159 is solved ?

**Comment by roy7** [comment]
Sure. We can reopen if it happens again.
