### ISSUE TITLE
Default host

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#6]
Should it be ggs.online-go.com instead of online-go.com? I find the first gives an instant response, whereas the second times out.

Default ggsport should be 443 as well. I know it is in the --devel branch but if you aren't ready to officially release the --devel changes maybe you should just pop in the host/port changes so new users don't get tripped up on that?

**Comment by anoek** [comment]
When v5 is released (which will coincide with devel getting merged into master), ggs.online-go.com will be going away

**Comment by roy7** [comment]
Ah okay, thanks. Maybe I'll catch you on forum or chat sometime, I can't get things to connect regardless of what I do (bot not found, id = 0 returned) but I'll keep trying. :)
