### ISSUE TITLE
place_free_handicap

### ISSUE THREAD

**Issue by lemonsqueeze** [online-go/gtp2ogs#70]
Follow up on #65 for the case where bot is playing black with handicap:

So we need to send place_free_handicap instead of genmove at the beginning. It returns all the stones at once so probably have to store them somewhere and return them one by one to server when asked. I'm not super familiar with gtp2ogs code so first idea was to re-engineer makeMove() to do it behind the scene and keep current interface, this way the rest of the code doesn't have to change.

**Comment by roy7** [comment]
Are you sure that function is used for free placement anywhere in the board, and not the static placement that Japanese rules use? I think that is only for Japanese, and the GTP specification even tells you the positions you have to do use for the first nine handicaps.

**Comment by lemonsqueeze** [comment]
You mean place_free_handicap ?
Yes, it's for free placement. fixed_handicap is the one for japanese rules according to [gtp spec](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html). We only support chinese rules here, right ?

**Comment by roy7** [comment]
Whoops I was on my phone. You are correct as usual. Although I notice Leela Zero when using place_free_handicap instantly returns standard fixed positions and doesn't think about the moves like it does under the current system (which will often move to other places like a 4-3 point).

Using place_free_handicap is probably more correct for general behavior though.

**Comment by lemonsqueeze** [comment]
Yeah, Pachi does the same too =)
Would you like to take care of this one ?
I have an idea but you know this part of the code much better than i do...

**Comment by roy7** [comment]
I probably wouldn't give it a try in the near future, but we can leave it as an open issue in case another volunteer decides to tackle it. :) Not many people give handicaps -to- bots though so it seems somewhat low priority? (Plus I'd probably override it in my personal Leela Zero bots.)

**Comment by lemonsqueeze** [comment]
Yeah, i don't see many people giving handicap to Leela in the near future =)
This is probably mostly of interest for weaker bots like gnugo etc...
