### ISSUE TITLE
Filter games on privacy setting

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#77]
It'd be nice to have a toggle for the bot to only play public games and reject all private games. (Or vica verse as the operator prefers.) Posting this as a future reminder to myself but maybe someone else would like to add the feature and submit a PR. :)

**Comment by wonderingabout** [comment]
`--privateonly` 
`--publiconly`

would need server support for `notification.private`, then it would be easy to write it if you want @anoek @roy7 :+1:
