### ISSUE TITLE
Support `place_free_handicap`

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#89]
The GTP spec calls for `place_free_handicap` to be called when handicap stones are placed.

IDK if other engines support it, but for my bot it would be helpful because for one then it would not have to guess how much handicap it is given (it technically takes handicap into account when playing) and also it would choose differently if it could play without white having a chance to play any stones.

I would probably be sending a PR for this if it sounds like one would be accepted.

If other engines do not support this, then I think this relies on also implementing detection of supported commands so `gtp2ogs` would know which engines to send the command to. Although a command line option would work too.

**Comment by windo** [comment]
Ah, when I say "GTP spec" I mean this:

https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html

I don't know how authoritative it is :)

**Comment by wonderingabout** [comment]
if you want to start a supported engine list, phoenixgo doesnt support the widespread `showboard` commad for example, see : 

https://github.com/online-go/gtp2ogs/commit/d5ebdbbde259a97c5ae1aed0ec42a07c9fbb2dbf

so i'm not sure phoenixgo would support it

also, the current implementation of free handicap works for both colors for phoenixgo (phoenixgo can place stones freely if it is given handicap, or let his opponents place the stones freely before playing without any issue)

i dont know about the techincal details of this issue though @windo

**Comment by windo** [comment]
Oh I see this is a duplicate of https://github.com/online-go/gtp2ogs/issues/70
