### ISSUE TITLE
gtp2ogs may hang when opponent resumes playing from scoring

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#90]
IDK know the exact circumstances, but I observed in one of my bot games that the opponent managed to refuse the autoscore results and resumed playing. However `gtp2ogs` did not call the bot to generate any more moves and just waited there. I manually restarted `gtp2ogs` and the play resumed.

This was with a few weeks old version. I do not currently have logging enabled so I can't figure out exactly what `gtp2ogs` was thinking when this happened.

**Comment by roy7** [comment]
Generally this should not be possible. Games with a bot are auto scored and human should not get an option to reject the auto score. @anoek

**Comment by windo** [comment]
I'm not able to find the game. It was a game with `amybot-beginner` today. I was following the game on the bot account so there is the possibility that it was me who somehow fumbled on the UI to resume the game from the bot side, though I don't think I did.

**Comment by windo** [comment]
Found it, it was this game:

https://online-go.com/game/16149100

**Comment by wonderingabout** [comment]
i didnt have such an issue (but i can see this behaviour more happening with 30k players lol)

**Comment by windo** [comment]
I tried reproducing this on the beta server but I think beta server might finalize scoring much faster due to it having no load. But sometimes when I observe bot games on the main server I can see the stone removal phase last for a few seconds (at least in the UI).

My "test" account on main server is currently playing SDK 9x9 games with real players so I don't want to mess with it too much. But I guess trying to reproduce on the main server (possibly during a high-load time) might be the next step here.

**Comment by wonderingabout** [comment]
@windo you can always have a official ogs testing account, like me here : 

https://online-go.com/player/602041/Aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

(well, give it a better name maybe "crashtest-bot-alpha" maybe
