### ISSUE TITLE
Refuse PASS moves as part of handicap

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#91]
This is more of an issue with my bot currently when it is confused by being allowed make a bunch of moves at the beginning of the game where it gets so confident in a win that it just passes. A player attempted to give the bot 18 handicap stones in a 9x9 game :)

I think the `PASS` also either confuses the server or `gtp2ogs` because after the first pass, `gtp2ogs` just hangs and does nothing with the game any more (until the `gtp2ogs` is restarted).

I think the correct solution here would be to reject the `PASS`, possibly resign/cancel the game and log something helpful about passes not being allowed as handicaps on the console.

**Comment by roy7** [comment]
@anoek Should PASS be an invalid move during handicap placement perhaps at the server level?

**Comment by wonderingabout** [comment]
@windo i advise you to use `--maxhandicap` lol

i dont see anything good in play more than 9 handicap on 19x19, and more than 4 on 9x9

maybe its a good opportunity to split handicap by boardsize : 

--minhandicap9
--maxhandicap9
--minhandicap13
--maxhandicap13
--minhandicap19
--maxhandicap19

then the same for ranked and unranked

**Comment by windo** [comment]
This was done as part of #96.
