### ISSUE TITLE
No tests for gtp2ogs

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#97]
It can be tricky to validate that changes don't cause regressions without any test coverage. At the very least, I think there should be some "smoke tests" for the integration of all the parts.

I'd like to split the `gtp2ogs.js` file into a "main file" and library file(s) (say `bot.js`, `game.js` and `connection.js`) so that the code could be loaded into test cases without triggering all of it to run end-to-end immediately. Then I'd like to add some basic test coverage that all the parts fit together - a basic integration test that mocks the GTP program and OGS server to behave well and confirm that `gtp2ogs` behaves relaying between the two. 

I haven't done a whole lot of node.js development, is `mocha` an acceptable module to use for testing? And `simple-mock` for mocking the GTP process and OGS server?

Does splitting up the main file into a few separately loadable files sound OK? Or should I try to keep as much of it together as possible and try to separate a minimal "entry point" file?

**Comment by roy7** [comment]
Perhaps @anoek can comment if he has any thoughts on this. I remember Leela Zero split some stuff on the server into multiple files last year and someone set up some tests, but honestly I didn't pay attention to that since testing is way outside of my experience. I know nothing about automated testing. :( Anoek probably knows a ton from the OGS server development though, perhaps he has a preferred tool/setup already.

In general though I have no objection to splitting things into smaller logical chunks and having some basic sort of tests added. :)

**Comment by windo** [comment]
So I was trying to do something like this:

https://github.com/online-go/gtp2ogs/commit/eaa1dadce47cbe70f1c06a8f18186b5a15bec95a

Basically, split the bulk of code into bot.js, game.js and connection.js, move all the argv and CONFIG variables to a config.js and add the most basic "integration test".

Does this approach seem feasible?

**Comment by wonderingabout** [comment]
i have no knowledge on the topic but this is very interesting if you can do it

i'll miss the old fat all in one gtp2ogs.js though, and the upgrade to devel instructions would need to be rewritten, but worth doing it 🏁

**Comment by lemonsqueeze** [comment]
Would be a good thing, yay.

Could setup github ci testing then so new PRs are tested automatically
(and more importantly have one of these fancy  ![passing](https://user-images.githubusercontent.com/2463904/51894827-14632d80-23a9-11e9-8058-7b58984846f9.png) flags =)

**Comment by windo** [comment]
I added the little build passing thing, it requires authorizing travisci to access the repo though.

**Comment by roy7** [comment]
This auto closed I think, but feel free to reopen or make a new issue for specific tests needed/etc if you wish. The basic #99 is merged though to get us started.

**Comment by wonderingabout** [comment]
yes, tests is very great if possible :1st_place_medal:
